module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order.Basic
public import Mathlib.Data.Set.Countable

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Cardinal

namespace PiBase.Spaces
namespace S155

/- Space 155: Fortissimo space of size ℵ₁.
See https://topology.pi-base.org/spaces/S000155.
Carrier: a set `X` of cardinality ℵ₁ with a distinguished point `p`; every point other
than `p` is isolated, and the neighborhoods of `p` are exactly the cocountable subsets
of `X` containing it — i.e. the topology is generated by the singletons `{x}`, `x ≠ p`,
together with the cocountable sets containing `p`. This is the one-point Lindelöfication
of a discrete space of size ℵ₁. -/

/-- The carrier: the canonical type of cardinality `ℵ₁`. -/
def S155 : Type := (ℵ₁ : Cardinal).ord.ToType

noncomputable instance instOrderBotToTypeAlephOne :
    OrderBot (ℵ₁ : Cardinal).ord.ToType :=
  Cardinal.toTypeOrderBot (Cardinal.aleph0_pos.trans Cardinal.aleph0_lt_aleph_one).ne'

/-- The distinguished point `p` (pi-Base S155): taken to be the least element of the
canonical well-ordering underlying the carrier. -/
noncomputable def p : S155 := (⊥ : (ℵ₁ : Cardinal).ord.ToType)

/-- The topology generated by the singletons of points other than `p` (making them
isolated) together with the cocountable sets containing `p` (making these exactly the
neighborhoods of `p`). -/
instance : TopologicalSpace S155 :=
  TopologicalSpace.generateFrom
    ({s : Set S155 | ∃ x : S155, x ≠ p ∧ s = {x}} ∪
      {s : Set S155 | p ∈ s ∧ sᶜ.Countable})

end S155
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S155 as a bundled `Space` (carrier + topology). -/
noncomputable def S155 : Space := ⟨PiBase.Spaces.S155.S155, inferInstance⟩

end PiBase.Formal
