module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S107

/- Space 107: Countable box product of reals.
See https://topology.pi-base.org/spaces/S000107.
The carrier is `ℕ → ℝ` (as for S30), but the topology is generated by full boxes
`∏ i, U i` for arbitrary `U : ℕ → Set ℝ` with each `U i` open in ℝ — i.e. no
finiteness restriction on which coordinates are constrained, unlike the ordinary
product topology. -/

/-- The countable box product of reals $\mathbb R^\omega$ with the box topology
(pi-Base S107). -/
def S107 : Type := ℕ → ℝ

instance S107_top : TopologicalSpace S107 :=
  TopologicalSpace.generateFrom
    {t : Set S107 | ∃ U : ℕ → Set ℝ, (∀ i, IsOpen (U i)) ∧ t = Set.pi Set.univ U}

end S107
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S107 as a bundled `Space` (carrier + topology). -/
noncomputable def S107 : Space := ⟨PiBase.Spaces.S107.S107, PiBase.Spaces.S107.S107_top⟩

end PiBase.Formal
