module

public import Mathlib.Topology.Order

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S187

/- Space 187: Right ray topology on a three-point set.
See https://topology.pi-base.org/spaces/S000187.
Carrier `Fin 3` (i.e. `X = {0, 1, 2}`); the topology is generated by the open right
rays `{x : y < x}` (i.e. `Set.Ioi y`) for each `y : Fin 3`, giving the opens
`{∅, {2}, {1, 2}, {0, 1, 2}}`. -/

/-- Right ray topology on a three-point set (pi-Base S187). -/
def S187 : Type := Fin 3

instance : TopologicalSpace S187 :=
  TopologicalSpace.generateFrom {s : Set (Fin 3) | ∃ y : Fin 3, s = Set.Ioi y}

instance : Finite S187 := inferInstanceAs (Finite (Fin 3))
instance : DecidableEq S187 := inferInstanceAs (DecidableEq (Fin 3))

end S187
end PiBase.Spaces
