module

public import Mathlib.Topology.Order
public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S95

/- Space 95: Concentric circles.
See https://topology.pi-base.org/spaces/S000095.
Carrier: `C₁ = {x ∈ ℝ² : |x| = 1}` and `C₂ = {x ∈ ℝ² : |x| = 2}`, `X = C₁ ∪ C₂`. The topology
is generated by the singletons `{x}` for `x ∈ C₂`, together with, for every open angular
interval `(a, b)` (an "open interval" of `C₁`), the set consisting of the corresponding open
arc of `C₁` unioned with the radial projection (onto `C₂`) of that arc minus its midpoint. -/

/-- The circle of radius `1` in the plane. -/
def S95.C1 : Set (ℝ × ℝ) := {p : ℝ × ℝ | p.1 ^ 2 + p.2 ^ 2 = 1}

/-- The circle of radius `2` in the plane. -/
def S95.C2 : Set (ℝ × ℝ) := {p : ℝ × ℝ | p.1 ^ 2 + p.2 ^ 2 = 4}

/-- Concentric circles (pi-Base S95): the union of the unit circle `C₁` and the circle `C₂`
of radius `2`, as a subset of the plane. -/
def S95 : Type := {p : ℝ × ℝ // p ∈ S95.C1 ∪ S95.C2}

namespace S95

/-- The open arc of `C₁` corresponding to the angular interval `(a, b)`. -/
noncomputable def arc (a b : ℝ) : Set (ℝ × ℝ) :=
  {p : ℝ × ℝ | ∃ θ ∈ Set.Ioo a b, p = (Real.cos θ, Real.sin θ)}

/-- The midpoint of the arc corresponding to the angular interval `(a, b)`. -/
noncomputable def arcMidpoint (a b : ℝ) : ℝ × ℝ := (Real.cos ((a + b) / 2), Real.sin ((a + b) / 2))

/-- Radial projection of a point of `C₁` onto `C₂`. -/
def project (p : ℝ × ℝ) : ℝ × ℝ := (2 * p.1, 2 * p.2)

/-- The generating open sets of the concentric-circles topology: the singletons of points of
`C₂`, together with, for every proper open angular interval `(a, b)` (`a < b ≤ a + 2π`), the
arc of `C₁` over `(a, b)` unioned with the radial projection of that arc minus its midpoint. -/
noncomputable def generators : Set (Set S95) :=
  { s | ∃ p : S95, p.1 ∈ C2 ∧ s = {p} } ∪
  { s | ∃ a b : ℝ, a < b ∧ b ≤ a + 2 * Real.pi ∧
      s = {p : S95 | p.1 ∈ arc a b ∨
        ∃ q ∈ arc a b, q ≠ arcMidpoint a b ∧ p.1 = project q} }

end S95

instance : TopologicalSpace S95 := TopologicalSpace.generateFrom S95.generators

end S95
end PiBase.Spaces
