module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S223

/- Space 223: the Ellentuck topology on $[\omega]^\omega$.
See https://topology.pi-base.org/spaces/S000223.
`X = [ω]^ω`, the infinite subsets of `ℕ`, topologized by the basis of sets
`[s, A] = {B ∈ X : s ⊆ B ⊆ s ∪ A ∧ max s < min (B \ s)}` for a finite `s ⊆ ω` and an
infinite `A ⊆ ω`. The side condition `max s < min (B \ s)` (with the π-Base convention
`max ∅ = -1`) is phrased without appeal to `max`/`min` directly, as "every element of `s`
is below every element of `B \ s`" — equivalent, including vacuously when `s = ∅`. -/

/-- The carrier `X = [ω]^ω`: the infinite subsets of `ℕ` (pi-Base S223). -/
def S223 : Type := {A : Set ℕ // A.Infinite}

namespace S223

/-- The basic open set `[s, A] = {B ∈ X : s ⊆ B ⊆ s ∪ A ∧ max s < min (B \ s)}`, for a
finite `s : Finset ℕ` and an infinite `A : Set ℕ`. The side condition is phrased as:
every element of `s` is less than every element of `B \ s`. -/
def basic (s : Finset ℕ) (A : Set ℕ) : Set S223 :=
  {B : S223 | (↑s ⊆ B.1) ∧ (B.1 ⊆ ↑s ∪ A) ∧ ∀ m ∈ s, ∀ n ∈ B.1 \ ↑s, m < n}

end S223

/-- The Ellentuck topology on `X = [ω]^ω`: generated by the basis
`{[s, A] : s ⊆ ω finite, A ⊆ ω infinite}`. -/
instance S223_top : TopologicalSpace S223 :=
  TopologicalSpace.generateFrom
    {u : Set S223 | ∃ (s : Finset ℕ) (A : Set ℕ), A.Infinite ∧ u = S223.basic s A}

end S223
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S223 as a bundled `Space` (carrier + topology). -/
noncomputable def S223 : Space := ⟨PiBase.Spaces.S223.S223, PiBase.Spaces.S223.S223_top⟩

end PiBase.Formal
