module

public import Mathlib.Topology.Basic
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S13

/- Space 13: Excluded point topology on ℝ.
See https://topology.pi-base.org/spaces/S000013.
Carrier `X = ℝ`; a set `U ⊆ ℝ` is open iff it excludes the particular point `p = 0`
or is the whole space. Generated by the subbasis of all sets not containing `0`,
together with the whole space `ℝ`. -/

/-- Excluded point topology on ℝ (pi-Base S13), excluding the point `0`. -/
def S13 : Type := ℝ

instance S13_top : TopologicalSpace S13 :=
  TopologicalSpace.generateFrom
    ({s : Set S13 | (0 : ℝ) ∉ s} ∪ {(Set.univ : Set S13)})

end S13
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S13 as a bundled `Space` (carrier + topology). -/
noncomputable def S13 : Space := ⟨PiBase.Spaces.S13.S13, PiBase.Spaces.S13.S13_top⟩

end PiBase.Formal
