module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S203

/- Space 203: Three-point set with the basis {{0}, X}.
See https://topology.pi-base.org/spaces/S000203.
X = {0, 1, 2} with open sets {∅, {0}, X}, generated by the single subbasic set {0}. -/

/-- Three-point set with the basis `{{0}, X}` (pi-Base S203). -/
def S203 : Type := Fin 3

instance : TopologicalSpace S203 := TopologicalSpace.generateFrom {({0} : Set (Fin 3))}

end S203
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S203 as a bundled `Space` (carrier + topology). -/
noncomputable def S203 : Space := ⟨PiBase.Spaces.S203.S203, inferInstance⟩

end PiBase.Formal
