module

public import Mathlib.Order.Filter.Ultrafilter.Defs
public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S110

/- Space 110: Strong ultrafilter topology.
See https://topology.pi-base.org/spaces/S000110.
Carrier `X = ω ⊔ M`, where `M` is the set of free ultrafilters on `ω`; the topology is
generated by the singletons `{n}` for `n ∈ ω`, together with the sets `A ∪ {F}` for
`F ∈ M` and `A ∈ F`. -/

/-- The free ultrafilters on `ℕ`, i.e. those not of the form `pure n`. -/
def S110.FreeUltrafilter : Type := {F : Ultrafilter ℕ // F ∉ Set.range (pure : ℕ → Ultrafilter ℕ)}

/-- The carrier of the strong ultrafilter topology (pi-Base S110):
`X = ω ⊔ M`, the natural numbers together with the free ultrafilters on `ω`. -/
def S110 : Type := ℕ ⊕ S110.FreeUltrafilter

/-- The subbasic open sets: singletons `{n}` of `ω`, and sets `A ∪ {F}` for `F` a free
ultrafilter on `ω` and `A ∈ F`. -/
def S110.subbasis : Set (Set S110) :=
  {s | ∃ n : ℕ, s = {Sum.inl n}} ∪
    {s | ∃ (F : S110.FreeUltrafilter) (A : Set ℕ), A ∈ F.val ∧
      s = Sum.inl '' A ∪ {Sum.inr F}}

instance S110_top : TopologicalSpace S110 := TopologicalSpace.generateFrom S110.subbasis

end S110
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S110 as a bundled `Space` (carrier + topology). -/
noncomputable def S110 : Space := ⟨PiBase.Spaces.S110.S110, PiBase.Spaces.S110.S110_top⟩

end PiBase.Formal
