module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order.Basic
public import Mathlib.Topology.Constructions.SumProd
public import Mathlib.Data.Real.Basic

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S81

/- Space 81: Alexandroff plank.
See https://topology.pi-base.org/spaces/S000081.
Carrier `[0,ω₁] × [-1,1]`: the ordinals at most the first uncountable ordinal ω₁, times the
real interval `[-1,1]`. Topology: generated by the open sets of the usual product topology
(order topology on each factor), together with all sets `U(α,n) = {(ω₁,0)} ∪ (α,ω₁] × (0,1/n)`
for `α < ω₁` and `n : ℕ` — these make `(ω₁,0)` a limit of the "plank" region approaching the
top-right corner along the deleted vertical strip. -/

/-- The ordinals at most the first uncountable ordinal `ω₁`. -/
def S81Ord : Type 1 := {o : Ordinal.{0} // o ≤ ω₁}

noncomputable instance : LinearOrder S81Ord :=
  inferInstanceAs (LinearOrder {o : Ordinal.{0} // o ≤ ω₁})

noncomputable instance : TopologicalSpace S81Ord := Preorder.topology S81Ord

instance : OrderTopology S81Ord := ⟨rfl⟩

/-- The real interval `[-1,1]`, carrying the usual (order) topology. -/
noncomputable instance : TopologicalSpace ↥(Set.Icc (-1 : ℝ) 1) :=
  Preorder.topology ↥(Set.Icc (-1 : ℝ) 1)

instance : OrderTopology ↥(Set.Icc (-1 : ℝ) 1) := ⟨rfl⟩

/-- Alexandroff plank (pi-Base S81): `[0,ω₁] × [-1,1]`. -/
def S81 : Type 1 := S81Ord × ↥(Set.Icc (-1 : ℝ) 1)

/-- The top element `ω₁ : S81Ord`, i.e. `ω₁` viewed as a point of `[0,ω₁]`. -/
noncomputable def S81Ord.top : S81Ord := ⟨ω₁, le_refl ω₁⟩

/-- The zero point `0 : [-1,1]`. -/
def S81Snd.zero : ↥(Set.Icc (-1 : ℝ) 1) := ⟨0, by norm_num⟩

/-- The top-right corner point `(ω₁, 0)` of the plank. -/
noncomputable def S81.corner : S81 := (S81Ord.top, S81Snd.zero)

/-- The extra generating sets `U(α,n) = {(ω₁,0)} ∪ (α,ω₁] × (0,1/n)` added to the usual
product topology, forming a neighborhood basis at the corner point along the deleted strip. -/
noncomputable def S81Extra : Set (Set S81) :=
  Set.range fun p : S81Ord × ℕ =>
    {S81.corner} ∪
      (Prod.fst ⁻¹' Set.Ioc p.1 S81Ord.top ∩
        Prod.snd ⁻¹' (Subtype.val ⁻¹' Set.Ioo (0 : ℝ) (1 / (p.2 + 1))))

/-- The generating sets for the topology on `S81`: the open sets of the usual product
(order) topology, together with the extra sets `U(α,n)`. -/
def S81Generators : Set (Set S81) :=
  {s | IsOpen[instTopologicalSpaceProd] s} ∪ S81Extra

instance : TopologicalSpace S81 := TopologicalSpace.generateFrom S81Generators

end S81
end PiBase.Spaces
