module

public import Mathlib.Analysis.InnerProductSpace.PiL2

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S68

/- Space 68: Deleted diameter topology.
See https://topology.pi-base.org/spaces/S000068.
Carrier `X = ℝ²` (as `EuclideanSpace ℝ (Fin 2)`, so `Metric.ball` gives genuine Euclidean
discs). The topology is generated by the basis of all open discs with their horizontal
diameter deleted, except the center point is kept: for center `c` and radius `r > 0`, the
basis set is `Metric.ball c r` minus all points of that ball on the horizontal line through
`c` (same second coordinate as `c`) other than `c` itself. -/

/-- Deleted diameter topology (pi-Base S68): the Euclidean plane ℝ². -/
def S68 : Type := EuclideanSpace ℝ (Fin 2)

/-- The basis of the deleted diameter topology: for each center `c` and radius `r > 0`,
the open disc of radius `r` about `c`, with the points on its horizontal diameter removed
(keeping the center `c` itself). -/
def S68Basis : Set (Set (EuclideanSpace ℝ (Fin 2))) :=
  Set.range fun p : (EuclideanSpace ℝ (Fin 2)) × {r : ℝ // 0 < r} =>
    Metric.ball p.1 p.2.1 \ {x : EuclideanSpace ℝ (Fin 2) | x 1 = p.1 1 ∧ x ≠ p.1}

instance : TopologicalSpace S68 := TopologicalSpace.generateFrom (S68Basis : Set (Set S68))

end S68
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S68 as a bundled `Space` (carrier + topology). -/
noncomputable def S68 : Space := ⟨PiBase.Spaces.S68.S68, inferInstance⟩

end PiBase.Formal
