module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S37

/- Space 37: ω₁+1 with endpoint doubled.
See https://topology.pi-base.org/spaces/S000037.
Carrier `X = [0,ω₁] ∪ {ω₁'}`: the ordinals below ω₁ (via `Sum.inl`), together with two
copies of the top point ω₁ (`Sum.inr false` for ω₁ itself, `Sum.inr true` for the doubled
point ω₁'). Opens are generated by: the usual order-open rays `Set.Iio o` and `Set.Ioi o`
on the ordinals below ω₁, together with, for each β < ω₁ and each copy `b` of the top point,
the set `(β,ω₁) ∪ {that copy}` — a neighborhood basis at each of the two doubled points. -/

/-- ω₁+1 with endpoint doubled (pi-Base S37): the ordinals below ω₁, together with two
copies of the top point ω₁. -/
def S37 : Type 1 := {o : Ordinal.{0} // o < ω₁} ⊕ Bool

/-- The generating sets for the topology on `S37`: order-open rays among the ordinals
below ω₁, and the doubled-point neighborhood-basis sets `(β,ω₁) ∪ {copy b of ω₁}`. -/
def S37Generators : Set (Set S37) :=
  (Set.range fun o : {o : Ordinal.{0} // o < ω₁} => Sum.inl '' Set.Iio o) ∪
  (Set.range fun o : {o : Ordinal.{0} // o < ω₁} => Sum.inl '' Set.Ioi o) ∪
  (Set.range fun p : {o : Ordinal.{0} // o < ω₁} × Bool =>
    (Sum.inl '' Set.Ioi p.1) ∪ {Sum.inr p.2})

instance S37_top : TopologicalSpace S37 := TopologicalSpace.generateFrom S37Generators

end S37
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S37 as a bundled `Space` (carrier + topology). -/
noncomputable def S37 : Space := ⟨PiBase.Spaces.S37.S37, PiBase.Spaces.S37.S37_top⟩

end PiBase.Formal
