module

public import Mathlib.Topology.Basic
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S45

/- Space 45: Overlapping interval topology.
See https://topology.pi-base.org/spaces/S000045.
Carrier `X = [-1, 1] ⊆ ℝ`; topology generated by the subbasis of all sets
`[-1, b)` with `b > 0` and `(a, 1]` with `a < 0`. -/

/-- Overlapping interval topology (pi-Base S45), on the interval `[-1, 1] ⊆ ℝ`. -/
def S45 : Type := ↥(Set.Icc (-1 : ℝ) 1)

instance : TopologicalSpace S45 :=
  TopologicalSpace.generateFrom
    {s : Set S45 |
      (∃ b : ℝ, b > 0 ∧ s = {x : S45 | (x.val : ℝ) < b}) ∨
        ∃ a : ℝ, a < 0 ∧ s = {x : S45 | a < (x.val : ℝ)}}

end S45
end PiBase.Spaces
