module

public import Mathlib.Order.PiLex
public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S214

/- Space 214: Lexicographically ordered ℤ^{ω₁}.
See https://topology.pi-base.org/spaces/S000214.
The carrier is the set of functions `ω₁.ToType → ℤ` (where `ω₁.ToType` is a concrete
well-ordered type of order type the first uncountable ordinal), ordered lexicographically,
and equipped with the order topology generated by the open rays of that order. -/

/-- Lexicographically ordered `ℤ^{ω₁}` (pi-Base S214). -/
def S214 : Type := Lex (Ordinal.ToType (Ordinal.omega 1) → ℤ)

noncomputable instance : LinearOrder S214 :=
  Pi.Lex.linearOrder (ι := Ordinal.ToType (Ordinal.omega 1)) (β := fun _ => ℤ)

noncomputable instance S214_top : TopologicalSpace S214 := Preorder.topology S214

end S214
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S214 as a bundled `Space` (carrier + topology). -/
noncomputable def S214 : Space := ⟨PiBase.Spaces.S214.S214, PiBase.Spaces.S214.S214_top⟩

end PiBase.Formal
