module

public import Mathlib.Topology.Order

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S200

/- Space 200: Right ray topology on ω.
See https://topology.pi-base.org/spaces/S000200.
ω = ℕ with opens generated by the right rays [n, →) = Set.Ici n for n < ω. -/

/-- Right ray topology on `ω` (pi-Base S200). -/
def S200 : Type := ℕ

instance : TopologicalSpace S200 :=
  TopologicalSpace.generateFrom {s : Set ℕ | ∃ n : ℕ, s = Set.Ici n}

end S200
end PiBase.Spaces
