module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S200

/- Space 200: Right ray topology on ω.
See https://topology.pi-base.org/spaces/S000200.
ω = ℕ with opens generated by the right rays [n, →) = Set.Ici n for n < ω. -/

/-- Right ray topology on `ω` (pi-Base S200). -/
def S200 : Type := ℕ

instance S200_top : TopologicalSpace S200 :=
  TopologicalSpace.generateFrom {s : Set ℕ | ∃ n : ℕ, s = Set.Ici n}

end S200
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S200 as a bundled `Space` (carrier + topology). -/
noncomputable def S200 : Space := ⟨PiBase.Spaces.S200.S200, PiBase.Spaces.S200.S200_top⟩

end PiBase.Formal
