module

public import Mathlib.Topology.Order.Basic
public import Mathlib.Data.Prod.Lex
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S41

/- Space 41: Lexicographically ordered unit square [0,1] × [0,1].
See https://topology.pi-base.org/spaces/S000041.
The carrier is the unit square, with the order topology generated by the
lexicographic order (compare first coordinates; break ties on the second). -/

/-- The lexicographically ordered unit square (pi-Base S41). -/
def S41 : Type := (Set.Icc (0 : ℝ) 1) ×ₗ (Set.Icc (0 : ℝ) 1)

noncomputable instance : LinearOrder S41 :=
  inferInstanceAs (LinearOrder ((Set.Icc (0 : ℝ) 1) ×ₗ (Set.Icc (0 : ℝ) 1)))

noncomputable instance : TopologicalSpace S41 := Preorder.topology S41

end S41
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S41 as a bundled `Space` (carrier + topology). -/
noncomputable def S41 : Space := ⟨PiBase.Spaces.S41.S41, inferInstance⟩

end PiBase.Formal
