module

public import PiBaseLean.Spaces.S79.Defs

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology OnePoint Ordinal

namespace PiBase.Spaces
namespace S88

/- Space 88: Tychonoff corkscrew.
See https://topology.pi-base.org/spaces/S000088.
The double-sided Jones machine `DJ(Y, H, K)` applied to `Y = S79` (the deleted Tychonoff
plank) and its two inseparable closed subsets `H` (the right edge, first coordinate `ω₁`)
and `K` (the top edge, second coordinate `∞`): take `Z = (Y × ℤ) ⊕ {p⁻, p⁺}` with the
topology generated by the basic opens `U ×ˢ {n}` (for `U` open in `Y`, `n : ℤ`) together
with the tail neighbourhoods `{p⁺} ∪ Y ×ˢ {n // n ≥ N}` and `{p⁻} ∪ Y ×ˢ {n // n ≤ -N}`
of the two new limit points, then quotient by gluing `(x, 2n) ~ (x, 2n+1)` for `x ∈ H` and
`(x, 2n-1) ~ (x, 2n)` for `x ∈ K` — alternately stitching consecutive copies of `Y` together
along `H` or `K` — carrying the quotient topology. -/

/-- The right edge `H` of the deleted Tychonoff plank `Y = S79`: points whose first
(the `[0, ω₁]`) coordinate equals `ω₁`. Together with `K`, these are the two closed
subsets of `Y` that cannot be separated by disjoint open sets. -/
def S88.H (x : S79) : Prop := x.val.1.val = ω₁

/-- The top edge `K` of the deleted Tychonoff plank `Y = S79`: points whose second
(the `[0, ω]`) coordinate equals `∞`. Together with `H`, these are the two closed
subsets of `Y` that cannot be separated by disjoint open sets. -/
def S88.K (x : S79) : Prop := x.val.2 = ∞

/-- The pre-quotient space `Z = (Y × ℤ) ⊕ Bool`: a two-sided sequence of copies of the
deleted Tychonoff plank `Y = S79`, indexed by `ℤ`, plus two extra points `p⁻ = inr false`
and `p⁺ = inr true`. -/
def S88.PreZ : Type 1 := (S79 × ℤ) ⊕ Bool

/-- The gluing relation on `S88.PreZ` underlying the double-sided Jones machine: reflexive
everywhere, and additionally identifying `(x, 2n)` with `(x, 2n+1)` for `x ∈ H`, and
`(x, 2n-1)` with `(x, 2n)` for `x ∈ K`, for every copy-index `n : ℤ`. Each point of
`Y × ℤ` is glued to at most one other point (since `H` and `K` are disjoint, a point of
`Y` lies in at most one of them), so this relation is already transitive. -/
def S88.glue : S88.PreZ → S88.PreZ → Prop
  | .inl (x, m), .inl (x', m') =>
      x = x' ∧ ((m = m') ∨
        (S88.H x ∧ ∃ n : ℤ, (m = 2 * n ∧ m' = 2 * n + 1) ∨ (m = 2 * n + 1 ∧ m' = 2 * n)) ∨
        (S88.K x ∧ ∃ n : ℤ, (m = 2 * n - 1 ∧ m' = 2 * n) ∨ (m = 2 * n ∧ m' = 2 * n - 1)))
  | .inr b, .inr b' => b = b'
  | .inl _, .inr _ => False
  | .inr _, .inl _ => False

theorem S88.glue_refl : ∀ a, S88.glue a a := by
  rintro (⟨x, m⟩ | b)
  · exact ⟨rfl, Or.inl rfl⟩
  · rfl

theorem S88.glue_symm : ∀ a b, S88.glue a b → S88.glue b a := by
  rintro (⟨x, m⟩ | b) (⟨x', m'⟩ | b') h
  · obtain ⟨rfl, h⟩ := h
    refine ⟨rfl, ?_⟩
    rcases h with h | ⟨hx, n, ⟨h1, h2⟩ | ⟨h1, h2⟩⟩ | ⟨hx, n, ⟨h1, h2⟩ | ⟨h1, h2⟩⟩
    · exact Or.inl h.symm
    · exact Or.inr (Or.inl ⟨hx, n, Or.inr ⟨h2, h1⟩⟩)
    · exact Or.inr (Or.inl ⟨hx, n, Or.inl ⟨h2, h1⟩⟩)
    · exact Or.inr (Or.inr ⟨hx, n, Or.inr ⟨h2, h1⟩⟩)
    · exact Or.inr (Or.inr ⟨hx, n, Or.inl ⟨h2, h1⟩⟩)
  · cases h
  · cases h
  · cases h; rfl

/-- A point `x ∈ Y` cannot lie in both edges `H` and `K`: that would force it to be the
corner point `(ω₁, ∞)`, which is excluded from `Y = S79`. -/
theorem S88.not_H_and_K (x : S79) : ¬ (S88.H x ∧ S88.K x) := by
  rintro ⟨hH, hK⟩
  apply x.property
  obtain ⟨⟨fst, snd⟩, hne⟩ := x
  simp only [S88.H, S88.K] at hH hK
  show (fst, snd) = S79.corner
  rw [S79.corner, Prod.mk.injEq]
  exact ⟨Subtype.ext hH, hK⟩

theorem S88.glue_trans : ∀ a b c, S88.glue a b → S88.glue b c → S88.glue a c := by
  rintro (⟨x, m⟩ | b) (⟨x', m'⟩ | b') (⟨x'', m''⟩ | b'') hab hbc
  · obtain ⟨rfl, hab⟩ := hab
    obtain ⟨rfl, hbc⟩ := hbc
    refine ⟨rfl, ?_⟩
    -- Each point is glued (non-reflexively) to at most one other point, via either `H`
    -- or `K` but not both; chaining two non-trivial steps from `m` would need `m` to have
    -- two distinct partners, which is impossible, so at least one step is the reflexive one.
    rcases hab with hab | ⟨hxH, n, hab⟩ | ⟨hxK, n, hab⟩
    · exact hab ▸ hbc
    · rcases hbc with hbc | ⟨_, n', hbc⟩ | ⟨hxK, _, hbc⟩
      · exact hbc ▸ (Or.inr (Or.inl ⟨hxH, n, hab⟩))
      · -- Two `H`-gluings in a row: either the parities clash (impossible), or the two
        -- steps cancel and `m = m''`, i.e. `a = c` and the reflexive clause applies.
        rcases hab with ⟨e1, e2⟩ | ⟨e1, e2⟩
        · rcases hbc with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact absurd (e2.symm.trans e3) (by omega)
          · exact Or.inl (by omega)
        · rcases hbc with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact Or.inl (by omega)
          · exact absurd (e2.symm.trans e3) (by omega)
      · exact absurd ⟨hxH, hxK⟩ (S88.not_H_and_K x)
    · rcases hbc with hbc | ⟨hxH, _, hbc⟩ | ⟨_, n', hbc⟩
      · exact hbc ▸ (Or.inr (Or.inr ⟨hxK, n, hab⟩))
      · exact absurd ⟨hxH, hxK⟩ (S88.not_H_and_K x)
      · -- Two `K`-gluings in a row: same parity argument as the `H` case above.
        rcases hab with ⟨e1, e2⟩ | ⟨e1, e2⟩
        · rcases hbc with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact absurd (e2.symm.trans e3) (by omega)
          · exact Or.inl (by omega)
        · rcases hbc with ⟨e3, e4⟩ | ⟨e3, e4⟩
          · exact Or.inl (by omega)
          · exact absurd (e2.symm.trans e3) (by omega)
  · cases hbc
  · cases hab
  · cases hab
  · cases hab
  · cases hbc
  · cases hbc
  · cases hab; cases hbc; rfl

instance S88.setoid : Setoid S88.PreZ where
  r := S88.glue
  iseqv := ⟨S88.glue_refl, fun {a b} => S88.glue_symm a b, fun {a b c} => S88.glue_trans a b c⟩

/-- The basic opens of `Z` coming from the product topology on `Y × ℤ` (with `ℤ` discrete):
a slice `U ×ˢ {n}` for `U` open in `Y` and `n : ℤ`. -/
def S88.prodBasic (U : Set S79) (n : ℤ) : Set S88.PreZ :=
  Sum.inl '' (U ×ˢ ({n} : Set ℤ))

/-- The tail neighbourhoods of the new limit point `p⁺ = inr true`: the point itself
together with every later copy `Y × {n // n ≥ N}`. -/
def S88.tailPos (N : ℤ) : Set S88.PreZ :=
  {Sum.inr true} ∪ Sum.inl '' ((Set.univ : Set S79) ×ˢ {n : ℤ | N ≤ n})

/-- The tail neighbourhoods of the new limit point `p⁻ = inr false`: the point itself
together with every earlier copy `Y × {n // n ≤ -N}`. -/
def S88.tailNeg (N : ℤ) : Set S88.PreZ :=
  {Sum.inr false} ∪ Sum.inl '' ((Set.univ : Set S79) ×ˢ {n : ℤ | n ≤ -N})

/-- The topology on `Z`, generated by the product-slice basic opens together with the tail
neighbourhoods of the two new limit points `p⁻, p⁺`. A set `U ⊆ Z` is a union of finite
intersections of these generators iff `U ∩ (Y × ℤ)` is open in the product topology (`ℤ`
discrete) and, whenever `U` contains `p⁺` (resp. `p⁻`), it contains some tail `Y × {n ≥ N}`
(resp. `Y × {n ≤ -N}`) — matching the π-Base description exactly. -/
instance S88.instTopologicalSpacePreZ : TopologicalSpace S88.PreZ :=
  TopologicalSpace.generateFrom
    ({s | ∃ U : Set S79, ∃ n : ℤ, IsOpen U ∧ s = S88.prodBasic U n} ∪
      {s | ∃ N : ℤ, s = S88.tailPos N} ∪
      {s | ∃ N : ℤ, s = S88.tailNeg N})

/-- Tychonoff corkscrew (pi-Base S88): the double-sided Jones machine applied to the
deleted Tychonoff plank `Y = S79` and its two inseparable closed edges `H, K`, realized
as the quotient `Z / ~` of the pre-quotient space `Z = (Y × ℤ) ⊕ Bool` by the gluing
relation `S88.glue`. -/
def S88 : Type 1 := Quotient S88.setoid

instance : TopologicalSpace S88 := instTopologicalSpaceQuotient

end S88
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S88 as a bundled `Space` (carrier + topology). -/
noncomputable def S88 : Space := ⟨PiBase.Spaces.S88.S88, inferInstance⟩

end PiBase.Formal
