module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Filter

namespace PiBase.Spaces
namespace S57

/- Space 57: Rational sequence topology.
See https://topology.pi-base.org/spaces/S000057.
Carrier `X = ℝ`. For each irrational `x` fix (via choice) a strictly monotone sequence of
rationals `ratSeq x : ℕ → ℚ` converging to `x` (exists since ℚ is dense in ℝ). The topology
is generated by declaring every rational singleton `{q}` open, together with the sets
`U_n(x) = {ratSeq x i : i > n} ∪ {x}` for each irrational `x` and `n : ℕ`, which form a
local basis at `x`. -/

/-- For every real `x`, a chosen strictly monotone sequence of rationals converging to `x`
(used, for irrational `x`, as the fixed approximating sequence in the rational sequence
topology). -/
noncomputable def ratSeq (x : ℝ) : ℕ → ℚ :=
  (Real.exists_seq_rat_strictMono_tendsto x).choose

/-- The tail-plus-limit sets `U_n(x) = {ratSeq x i : i > n} ∪ {x}`, the local basis at an
irrational point `x` in the rational sequence topology. -/
def tailNbhd (x : ℝ) (n : ℕ) : Set ℝ :=
  {y : ℝ | ∃ i > n, y = ((ratSeq x i : ℚ) : ℝ)} ∪ {x}

/-- Rational sequence topology on ℝ (pi-Base S57). -/
def S57 : Type := ℝ

/-- Generated by the rational singletons together with the local-basis sets `tailNbhd x n`
at each irrational `x`. -/
noncomputable instance : TopologicalSpace S57 :=
  TopologicalSpace.generateFrom
    ({s : Set S57 | ∃ q : ℚ, s = {((q : ℚ) : ℝ)}} ∪
      {s : Set S57 | ∃ x : ℝ, Irrational x ∧ ∃ n : ℕ, s = tailNbhd x n})

end S57
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S57 as a bundled `Space` (carrier + topology). -/
noncomputable def S57 : Space := ⟨PiBase.Spaces.S57.S57, inferInstance⟩

end PiBase.Formal
