module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S136

/- Space 136: Bing's Example G.
See https://topology.pi-base.org/spaces/S000136.
Carrier X = 2^(2^ℝ), i.e. functions from `Set ℝ` to `Bool`. For `r : ℝ`, `xr r` is the
point sending `S : Set ℝ` to `true` iff `r ∈ S`; `M` is the range of `r ↦ xr r`. The
topology is generated by the usual (product-topology) subbasic opens together with a
singleton `{x}` for every `x ∉ M` — i.e. points of `M` keep their usual product
neighborhoods, and every point outside `M` is isolated. -/

/-- The carrier of Bing's Example G: `2^(2^ℝ)`, i.e. functions `Set ℝ → Bool`. -/
def S136 : Type := Set ℝ → Bool

namespace S136

/-- The point `xr r : Set ℝ → Bool` sends `S` to `true` iff `r ∈ S`. -/
noncomputable def xr (r : ℝ) : S136 := fun S => @decide (r ∈ S) (Classical.propDecidable _)

/-- `M`, the set of "product-topology" points `{xr r : r ∈ ℝ}` inside `X`. -/
noncomputable def M : Set S136 := Set.range xr

end S136

/-- The topology on `S136`: generated by the subbasic opens of the product topology on
`Set ℝ → Bool` (discrete `Bool` factors), together with singletons of every point
outside `M` — so points of `M` retain their usual product neighborhoods and every point
of `X \ M` is isolated. -/
instance : TopologicalSpace S136 :=
  TopologicalSpace.generateFrom
    ({s : Set S136 | IsOpen[Pi.topologicalSpace] s} ∪ {s : Set S136 | ∃ x ∉ S136.M, s = {x}})

end S136
end PiBase.Spaces
