module

public import Mathlib.Topology.Order
public import Mathlib.Algebra.Order.Ring.Rat

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S151

/- Space 151: Right "open-ray" topology on $[0,1]\cap\mathbb Q$.
See https://topology.pi-base.org/spaces/S000151.
Carrier `{q : ℚ // 0 ≤ q ∧ q ≤ 1}` (i.e. `[0,1] ∩ ℚ` with the order induced
from ℝ); the topology is generated by the base consisting of the whole space
together with all the open rays `(x, →) = {y | x < y}` for `x` in the carrier. -/

/-- Right "open-ray" topology on `[0,1] ∩ ℚ` (pi-Base S151): the carrier is
`{q : ℚ // 0 ≤ q ∧ q ≤ 1}`. -/
def S151 : Type := {q : ℚ // 0 ≤ q ∧ q ≤ 1}

instance : LinearOrder S151 := inferInstanceAs (LinearOrder {q : ℚ // 0 ≤ q ∧ q ≤ 1})

/-- The generating open sets: the whole carrier, together with every open ray
`(x, →)` for `x` in the carrier. -/
instance : TopologicalSpace S151 :=
  TopologicalSpace.generateFrom
    ({(Set.univ : Set S151)} ∪ {s : Set S151 | ∃ x : S151, s = Set.Ioi x})

end S151
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S151 as a bundled `Space` (carrier + topology). -/
noncomputable def S151 : Space := ⟨PiBase.Spaces.S151.S151, inferInstance⟩

end PiBase.Formal
