module

public import Mathlib.Topology.Order
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S86

/- Space 86: Everywhere doubled line.
See https://topology.pi-base.org/spaces/S000086.
Carrier `X = ℝ × Bool`, i.e. two copies of the real line, `A = ℝ × {false}` and
`B = ℝ × {true}`. The topology is generated by the basic open sets
`B(⟨x, i⟩, ε) = {⟨x, i⟩} ∪ ((Ioo (x - ε) x ∪ Ioo x (x + ε)) ×ˢ {false})`
for each point `⟨x, i⟩ : X` and `ε > 0`: a neighborhood of a point keeps its own label
but only ever reaches into the lower copy `A`, via a punctured Euclidean neighborhood. -/

/-- Everywhere doubled line (pi-Base S86): two copies of ℝ, with every point's
neighborhoods built from a punctured Euclidean neighborhood in the `false` copy. -/
def S86 : Type := ℝ × Bool

/-- The basic open set `B(⟨x, i⟩, ε)` at the point `⟨x, i⟩` for radius `ε > 0`:
the point itself, together with the punctured Euclidean `ε`-neighborhood of `x`
sitting in the `false` copy. -/
def basicOpen (x : ℝ) (i : Bool) (ε : ℝ) : Set S86 :=
  {(x, i)} ∪ ((Set.Ioo (x - ε) x ∪ Set.Ioo x (x + ε)) ×ˢ ({false} : Set Bool))

instance : TopologicalSpace S86 :=
  TopologicalSpace.generateFrom
    {s : Set S86 | ∃ x : ℝ, ∃ i : Bool, ∃ ε : ℝ, ε > 0 ∧ s = basicOpen x i ε}

end S86
end PiBase.Spaces
