module

public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Algebra.Group.Basic
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S179

/- Space 179: The Peng-Wu Group.
See https://topology.pi-base.org/spaces/S000179.
A subgroup `grp(𝓛)` of `ℝ^{ω₁}` (coordinatewise addition, product topology), generated by a
subset `𝓛` of cardinality `ω₁`, constructed in Section 4 of Peng-Wu ("A Lindelöf group with
non-Lindelöf square", doi:10.1016/j.aim.2017.11.021) to produce a Lindelöf (P18) topological
group (P87) whose square is not Lindelöf. -/

/-- The index set for the ambient product `ℝ^{ω₁}`: the countable ordinals, which has
cardinality `ℵ₁`. -/
def S179.Idx : Type 1 := {o : Ordinal.{0} // o < ω₁}

/-- The ambient group `ℝ^{ω₁}`, coordinatewise addition, product topology. -/
def S179.Amb : Type 1 := S179.Idx → ℝ

noncomputable instance : AddCommGroup S179.Amb := inferInstanceAs (AddCommGroup (S179.Idx → ℝ))

instance : TopologicalSpace S179.Amb :=
  inferInstanceAs (TopologicalSpace (S179.Idx → ℝ))

instance : IsTopologicalAddGroup S179.Amb :=
  inferInstanceAs (IsTopologicalAddGroup (S179.Idx → ℝ))

/-- Stand-in generating set for `𝓛`: the "coordinate delta" points of `ℝ^{ω₁}`, one per index.
This set has cardinality `ℵ₁` (as does `S179.Idx`), matching the cardinality of `𝓛` in the
source, but is NOT the specific set constructed in Section 4 of Peng-Wu -- that construction is
a delicate combinatorial choice (designed so that `grp(𝓛)` is Lindelöf but `grp(𝓛)^2` is not)
which is not reproduced here.
-- TODO: replace with the actual Peng-Wu generating set `𝓛` if/when that combinatorics is
-- formalized; the traits P18 (Lindelöf) / ¬P18 for the square depend on the specific choice. -/
noncomputable def S179.L : Set S179.Amb :=
  open Classical in Set.range fun i : S179.Idx => fun j : S179.Idx => if j = i then (1 : ℝ) else 0

/-- The subgroup of `ℝ^{ω₁}` generated by `S179.L`. -/
noncomputable def S179.Grp : AddSubgroup S179.Amb := AddSubgroup.closure S179.L

/-- The Peng-Wu group (pi-Base S179): the subgroup `grp(𝓛)` of `ℝ^{ω₁}` generated by a subset
`𝓛` of cardinality `ω₁`, carrying the subspace topology from the product topology on `ℝ^{ω₁}`. -/
def S179 : Type 1 := ↥S179.Grp

noncomputable instance : AddCommGroup S179 := inferInstanceAs (AddCommGroup ↥S179.Grp)

instance S179_top : TopologicalSpace S179 :=
  TopologicalSpace.induced (Subtype.val : S179 → S179.Amb) inferInstance

end S179
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S179 as a bundled `Space` (carrier + topology). -/
noncomputable def S179 : Space := ⟨PiBase.Spaces.S179.S179, PiBase.Spaces.S179.S179_top⟩

end PiBase.Formal
