module

public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Topology.Constructions

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S64

/- Space 64: Rational extension of the plane.
See https://topology.pi-base.org/spaces/S000064.
The carrier is ℝ × ℝ (the Euclidean plane); the topology is generated by the sets
{x} ∪ (D ∩ U), for U Euclidean-open in ℝ × ℝ and x ∈ U, where D = ℚ × ℚ. -/

/-- Rational extension of the plane (pi-Base S64). -/
def S64 : Type := ℝ × ℝ

instance : TopologicalSpace S64 :=
  TopologicalSpace.generateFrom
    {s : Set (ℝ × ℝ) | ∃ U : Set (ℝ × ℝ), IsOpen U ∧ ∃ x ∈ U,
      s = {x} ∪ ((Set.range ((↑) : ℚ → ℝ) ×ˢ Set.range ((↑) : ℚ → ℝ)) ∩ U)}

end S64
end PiBase.Spaces
