module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S129

/- Space 129: Wheel without its hub.
See https://topology.pi-base.org/spaces/S000129.
Carrier `X = {(x, y) ∈ ℝ² : 0 < x² + y² ≤ 1}` (the closed unit disc with the origin
removed). The topology is generated by the Euclidean-open subsets of `X` (restricted
from the standard topology on `ℝ × ℝ`), together with, for every unit vector `q` and
every open subinterval `(a, b) ⊆ (0, 1]`, the open "radius interval"
`{λ • q : λ ∈ (a, b)}`. -/

/-- The carrier of the wheel-without-its-hub space (pi-Base S129): the closed unit disc
in `ℝ × ℝ` with the origin removed. -/
def S129.carrier : Set (ℝ × ℝ) := {p : ℝ × ℝ | 0 < p.1 ^ 2 + p.2 ^ 2 ∧ p.1 ^ 2 + p.2 ^ 2 ≤ 1}

/-- Wheel without its hub (pi-Base S129). -/
def S129 : Type := ↥S129.carrier

/-- The generating open sets for the wheel-without-its-hub topology: the Euclidean-open
subsets of `X` (i.e. traces of Euclidean-open subsets of `ℝ × ℝ` on `X`), together with,
for every unit vector `q` (a point of the boundary circle) and every open subinterval
`(a, b) ⊆ (0, 1]`, the open radius interval `{λ • q : λ ∈ (a, b)}`. -/
def S129.generators : Set (Set S129) :=
  {s | ∃ U : Set (ℝ × ℝ), IsOpen U ∧ s = {p : S129 | p.1 ∈ U}} ∪
  {s | ∃ q : ℝ × ℝ, q.1 ^ 2 + q.2 ^ 2 = 1 ∧ ∃ a b : ℝ, 0 ≤ a ∧ b ≤ 1 ∧
    s = {p : S129 | ∃ lam : ℝ, lam ∈ Set.Ioo a b ∧ p.1 = (lam * q.1, lam * q.2)}}

instance : TopologicalSpace S129 := TopologicalSpace.generateFrom S129.generators

end S129
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S129 as a bundled `Space` (carrier + topology). -/
noncomputable def S129 : Space := ⟨PiBase.Spaces.S129.S129, inferInstance⟩

end PiBase.Formal
