module

public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S69

/- Space 69: Deleted radius topology.
See https://topology.pi-base.org/spaces/S000069.
On X = ℝ × ℝ (the plane), the topology is generated by the subbasis of all open
discs with their right horizontal radius (excluding the center) deleted:
for center (a, b) and radius r > 0,
  { (x, y) | (x - a)^2 + (y - b)^2 < r^2 } \ { (x, b) | a < x ∧ x < a + r }. -/

/-- Deleted radius topology (pi-Base S69), carrier: the plane ℝ × ℝ. -/
def S69 : Type := ℝ × ℝ

/-- The subbasis: open discs of center `(a, b)` and radius `r > 0`, with the
open right horizontal radius (excluding the center) deleted. -/
def S69.subbasis : Set (Set (ℝ × ℝ)) :=
  { s | ∃ a b : ℝ, ∃ r : ℝ, 0 < r ∧
      s = { p : ℝ × ℝ | (p.1 - a) ^ 2 + (p.2 - b) ^ 2 < r ^ 2 } \
          { p : ℝ × ℝ | p.2 = b ∧ a < p.1 ∧ p.1 < a + r } }

instance : TopologicalSpace S69 := TopologicalSpace.generateFrom S69.subbasis

end S69
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S69 as a bundled `Space` (carrier + topology). -/
noncomputable def S69 : Space := ⟨PiBase.Spaces.S69.S69, inferInstance⟩

end PiBase.Formal
