module

public import Mathlib.Topology.Order
public import Mathlib.Order.Interval.Set.Defs
public import Mathlib.Data.Real.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S43

/- Space 43: Sorgenfrey line.
See https://topology.pi-base.org/spaces/S000043.
ℝ with the topology generated by the basis of right half-open intervals `[a, b)`. -/

/-- The Sorgenfrey line (π-Base S43): `ℝ` with the lower limit topology, generated by
the basis of right half-open intervals `[a, b)`. -/
def S43 : Type := ℝ

instance : TopologicalSpace S43 :=
  TopologicalSpace.generateFrom {U : Set ℝ | ∃ a b : ℝ, U = Set.Ico a b}

end S43
end PiBase.Spaces
