module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S63

/- Space 63: Michael line.
See https://topology.pi-base.org/spaces/S000063.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
all singletons `{x}` for `x` irrational (so every subset of the irrationals is open). -/

/-- Michael line (pi-Base S63). -/
def S63 : Type := ℝ

instance S63_top : TopologicalSpace S63 :=
  TopologicalSpace.generateFrom
    ({U : Set ℝ | IsOpen U} ∪ {V : Set ℝ | ∃ x : ℝ, Irrational x ∧ V = {x}})

end S63
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S63 as a bundled `Space` (carrier + topology). -/
noncomputable def S63 : Space := ⟨PiBase.Spaces.S63.S63, PiBase.Spaces.S63.S63_top⟩

end PiBase.Formal
