module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S63

/- Space 63: Michael line.
See https://topology.pi-base.org/spaces/S000063.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
all singletons `{x}` for `x` irrational (so every subset of the irrationals is open). -/

/-- Michael line (pi-Base S63). -/
def S63 : Type := ℝ

instance : TopologicalSpace S63 :=
  TopologicalSpace.generateFrom
    ({U : Set ℝ | IsOpen U} ∪ {V : Set ℝ | ∃ x : ℝ, Irrational x ∧ V = {x}})

end S63
end PiBase.Spaces
