module

public import Mathlib.Data.Real.Sqrt
public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Topology.Constructions

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S72

/- Space 72: Arens square.
See https://topology.pi-base.org/spaces/S000072.
Carrier: `X = S ∪ {⟨0,0⟩, ⟨1,0⟩} ∪ {⟨1/2, r√2⟩ : r ∈ (0, 1/√2) ∩ ℚ} ⊆ ℝ × ℝ`, where
`S = ((0,1) ∩ ℚ \ {1/2}) × ((0,1) ∩ ℚ)`. Topology: points of `S` carry their usual
Euclidean-subspace neighborhoods; `⟨0,0⟩`, `⟨1,0⟩` and each `⟨1/2, r√2⟩` instead carry
the explicit local bases `Uₙ(0,0)`, `Uₙ(1,0)`, `Uₙ(1/2, r√2)` from Counterexamples in
Topology #80, generated here as a subbasis together with the `S`-traces. -/

/-- Rationals in the open unit interval `(0, 1)`. -/
def S72.Q01 : Set ℝ := Set.range ((↑) : ℚ → ℝ) ∩ Set.Ioo (0 : ℝ) 1

/-- The "generic" part `S` of the Arens square: `((0,1) ∩ ℚ \ {1/2}) × ((0,1) ∩ ℚ)`. -/
def S72.genericPart : Set (ℝ × ℝ) := (S72.Q01 \ {(1 / 2 : ℝ)}) ×ˢ S72.Q01

/-- The special column `{⟨1/2, r√2⟩ : r ∈ ℚ, 0 < r < 1/√2}`. -/
def S72.specialColumn : Set (ℝ × ℝ) :=
  {p : ℝ × ℝ | ∃ r : ℚ, 0 < (r : ℝ) ∧ (r : ℝ) < 1 / Real.sqrt 2 ∧
    p = (1 / 2, (r : ℝ) * Real.sqrt 2)}

/-- The carrier `X` of the Arens square. -/
def S72.carrier : Set (ℝ × ℝ) :=
  S72.genericPart ∪ {((0 : ℝ), (0 : ℝ)), ((1 : ℝ), (0 : ℝ))} ∪ S72.specialColumn

/-- Arens square (pi-Base S72), as a subtype of `ℝ × ℝ`. -/
def S72 : Type := ↥S72.carrier

/-- The local basis `Uₙ(0,0) = {⟨0,0⟩} ∪ ((0,1/4) ∩ ℚ) × ((0,1/n) ∩ ℚ)` at the corner
point `⟨0,0⟩`. -/
def S72.U0 (n : ℕ) : Set (ℝ × ℝ) :=
  {((0 : ℝ), (0 : ℝ))} ∪
    ((Set.range ((↑) : ℚ → ℝ) ∩ Set.Ioo (0 : ℝ) (1 / 4)) ×ˢ
      (Set.range ((↑) : ℚ → ℝ) ∩ Set.Ioo (0 : ℝ) (1 / (n : ℝ))))

/-- The local basis `Uₙ(1,0) = {⟨1,0⟩} ∪ ((3/4,1) ∩ ℚ) × ((0,1/n) ∩ ℚ)` at the corner
point `⟨1,0⟩`. -/
def S72.U1 (n : ℕ) : Set (ℝ × ℝ) :=
  {((1 : ℝ), (0 : ℝ))} ∪
    ((Set.range ((↑) : ℚ → ℝ) ∩ Set.Ioo (3 / 4 : ℝ) 1) ×ˢ
      (Set.range ((↑) : ℚ → ℝ) ∩ Set.Ioo (0 : ℝ) (1 / (n : ℝ))))

/-- The local basis `Uₙ(1/2, r√2) = ((1/4,3/4) × (r√2 - 1/n, r√2 + 1/n)) ∩ X` at a
special-column point `⟨1/2, r√2⟩`. -/
def S72.Ucol (r : ℚ) (n : ℕ) : Set (ℝ × ℝ) :=
  (Set.Ioo (1 / 4 : ℝ) (3 / 4) ×ˢ
      Set.Ioo ((r : ℝ) * Real.sqrt 2 - 1 / (n : ℝ)) ((r : ℝ) * Real.sqrt 2 + 1 / (n : ℝ))) ∩
    S72.carrier

/-- The topology on the Arens square: generated by the traces of Euclidean-open sets on
the generic part `S` (giving points of `S` their usual subspace neighborhoods), together
with the local bases `Uₙ(0,0)`, `Uₙ(1,0)` and `Uₙ(1/2, r√2)` at the three special families
of points. -/
instance : TopologicalSpace S72 :=
  TopologicalSpace.generateFrom
    ({s : Set S72 | ∃ (x : ℝ × ℝ) (_ : x ∈ S72.genericPart) (U : Set (ℝ × ℝ)),
        IsOpen U ∧ x ∈ U ∧ s = {y : S72 | y.val ∈ S72.genericPart ∧ y.val ∈ U}} ∪
      {s : Set S72 | ∃ n : ℕ, s = {y : S72 | y.val ∈ S72.U0 n}} ∪
      {s : Set S72 | ∃ n : ℕ, s = {y : S72 | y.val ∈ S72.U1 n}} ∪
      {s : Set S72 | ∃ (r : ℚ) (n : ℕ), s = {y : S72 | y.val ∈ S72.Ucol r n}})

end S72
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S72 as a bundled `Space` (carrier + topology). -/
noncomputable def S72 : Space := ⟨PiBase.Spaces.S72.S72, inferInstance⟩

end PiBase.Formal
