module

public import Mathlib.Topology.Order
public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Data.PNat.Basic
public import Mathlib.Data.Set.Card

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Filter

namespace PiBase.Spaces
namespace S96

/- Space 96: Appert space.
See https://topology.pi-base.org/spaces/S000096.
Carrier is the positive integers `ℕ+`; for `S ⊆ ℕ+` and `n : ℕ+`, let
`N n S = |{m ∈ S | m < n}|`. A set `U` is declared open iff `1 ∉ U`, or
`1 ∈ U` and the density `N n U / n` tends to `1` as `n → ∞`.
The topology is generated by exactly this family of sets. -/

/-- For `n : ℕ+` and `S : Set ℕ+`, the count of elements of `S` below `n`. -/
noncomputable def apertCount (n : ℕ+) (S : Set ℕ+) : ℕ := {m ∈ S | m < n}.ncard

/-- The family of pi-Base-open subsets of the Appert space:
sets not containing `1`, together with sets containing `1` whose lower density is `1`. -/
def AppertOpen (U : Set ℕ+) : Prop :=
  (1 : ℕ+) ∉ U ∨
    ((1 : ℕ+) ∈ U ∧
      Tendsto (fun n : ℕ+ => (apertCount n U : ℝ) / (n : ℕ)) atTop (nhds 1))

/-- Appert space (pi-Base S96). -/
def S96 : Type := ℕ+

instance : TopologicalSpace S96 := TopologicalSpace.generateFrom {U : Set ℕ+ | AppertOpen U}

end S96
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S96 as a bundled `Space` (carrier + topology). -/
noncomputable def S96 : Space := ⟨PiBase.Spaces.S96.S96, inferInstance⟩

end PiBase.Formal
