module

public import Mathlib.Topology.Order
public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Data.Set.Countable

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S55

/- Space 55: Countable complement extension topology on the real numbers.
See https://topology.pi-base.org/spaces/S000055.
On `X = ℝ`, the topology is the smallest one generated by the union of the
Euclidean open sets (S25) and the cocountable-or-empty sets (S17). -/

/-- Countable complement extension topology on ℝ (pi-Base S55). -/
def S55 : Type := ℝ

instance S55_top : TopologicalSpace S55 :=
  TopologicalSpace.generateFrom
    ({s : Set S55 | IsOpen (X := ℝ) s} ∪ {s : Set S55 | s = ∅ ∨ sᶜ.Countable})

end S55
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S55 as a bundled `Space` (carrier + topology). -/
noncomputable def S55 : Space := ⟨PiBase.Spaces.S55.S55, PiBase.Spaces.S55.S55_top⟩

end PiBase.Formal
