module

public import Mathlib.Topology.Order
public import Mathlib.Order.Interval.Set.Defs
public import Mathlib.Order.WithBot

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S160

/- Space 160: Right "open-ray" topology on ω+1.
See https://topology.pi-base.org/spaces/S000160.
The carrier ω+1 is ℕ with a top point adjoined; the topology is generated by
`X` itself together with the upper rays `(a, ⊤]` for `a ∈ X`. -/

/-- Right "open-ray" topology on `ω+1` (pi-Base S160): the carrier is `ℕ` with a top
point adjoined, and the open sets are exactly `X` and the upper rays `(a, ⊤]` for `a ∈ X`. -/
def S160 : Type := WithTop ℕ

instance : LinearOrder S160 := inferInstanceAs (LinearOrder (WithTop ℕ))

instance : TopologicalSpace S160 :=
  TopologicalSpace.generateFrom
    ({Set.univ} ∪ {U : Set S160 | ∃ a : S160, U = Set.Ioi a})

end S160
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S160 as a bundled `Space` (carrier + topology). -/
noncomputable def S160 : Space := ⟨PiBase.Spaces.S160.S160, inferInstance⟩

end PiBase.Formal
