module

public import Mathlib.Topology.Constructions
public import Mathlib.SetTheory.Cardinal.Aleph

@[expose] public section

open Topology
open scoped Ordinal

namespace PiBase.Spaces
namespace S174

/- Space 174: Pol's T₆ non-paracompact space.
See https://topology.pi-base.org/spaces/S000174.
The carrier is `X = ω₁^ω` (functions `ℕ → ω₁`, with `ω₁` discrete); the topology is
generated by the basis `U ∩ ξ^ω`, where `ξ < ω₁` and `U` is open in the product topology. -/

/-- The discrete space of ordinals below `ω₁` (the first uncountable ordinal), i.e. `ω₁`
itself viewed as a `Type` via `Ordinal.ToType`. -/
def Omega1 : Type := (ω₁ : Ordinal).ToType

noncomputable instance : LinearOrder Omega1 := inferInstanceAs (LinearOrder (ω₁ : Ordinal).ToType)

instance : TopologicalSpace Omega1 := ⊥

/-- The carrier `ω₁^ω`: functions from `ℕ` into `ω₁`. -/
def S174 : Type := ℕ → Omega1

/-- The product topology on `ℕ → ω₁`, with `ω₁` discrete. -/
instance productTop : TopologicalSpace (ℕ → Omega1) := Pi.topologicalSpace

/-- For `ξ : ω₁`, the "initial segment power" `ξ^ω ⊆ ω₁^ω`: functions everywhere below `ξ`. -/
def segPow (ξ : Omega1) : Set (ℕ → Omega1) :=
  Set.pi Set.univ fun _ => Set.Iio ξ

/-- The topology on `S174 = ω₁^ω` generated by the basis `{U ∩ ξ^ω : ξ < ω₁, U open in the
product topology}`. -/
instance : TopologicalSpace S174 :=
  TopologicalSpace.generateFrom
    {s : Set (ℕ → Omega1) | ∃ (U : Set (ℕ → Omega1)) (ξ : Omega1),
      IsOpen[productTop] U ∧ s = U ∩ segPow ξ}

end S174
end PiBase.Spaces
