module

public import Mathlib.Topology.Order
public import Mathlib.Data.Set.Countable
public import Mathlib.SetTheory.Cardinal.Aleph

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S157

/- Space 157: Fortissimo space of size ℵ₂.
See https://topology.pi-base.org/spaces/S000157.
Carrier: a set `X` of cardinality ℵ₂ (realized as `(aleph 2).ord.toType`) with the
distinguished point `p := ⊥` (the least element of this well-ordered type): every point
other than `p` is isolated, and the neighborhoods of `p` are exactly the cocountable
sets containing it — i.e. the topology is generated by the singletons `{x}`, `x ≠ p`,
together with the cocountable sets containing `p`. -/

/-- The carrier of the Fortissimo space of size ℵ₂ (pi-Base S157): the order type of the
cardinal ℵ₂, which has cardinality exactly ℵ₂ by `Cardinal.mk_ord_toType`. -/
def S157 : Type := (Cardinal.aleph 2).ord.ToType

noncomputable instance : LinearOrder S157 :=
  inferInstanceAs (LinearOrder (Cardinal.aleph 2).ord.ToType)

noncomputable instance : OrderBot S157 :=
  Cardinal.toTypeOrderBot (c := Cardinal.aleph 2) (Cardinal.aleph_pos 2).ne'

/-- The distinguished point of `S157`: the least element of the well-order. -/
noncomputable def S157.p : S157 := ⊥

/-- The topology generated by the singletons of points other than `p` (making them
isolated) together with the cocountable sets containing `p` (making these exactly the
neighborhoods of `p`). -/
noncomputable instance : TopologicalSpace S157 :=
  TopologicalSpace.generateFrom
    ({s : Set S157 | ∃ x : S157, x ≠ S157.p ∧ s = {x}} ∪
      {s : Set S157 | S157.p ∈ s ∧ sᶜ.Countable})

end S157
end PiBase.Spaces
