module

public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S192

/- Space 192: Modified telophase topology.
See https://topology.pi-base.org/spaces/S000192.
Carrier `X = [0,∞) ∪ {∞_E, ∞_D}` (via `Sum.inl` for `[0,∞)` and `Sum.inr false / Sum.inr true`
for the two added points `∞_E`, `∞_D`). Opens are generated by: the usual order-open rays
`Set.Iio x` and `Set.Ioi x` on `[0,∞)`, giving every point of `[0,∞)` its ordinary subspace
neighborhoods, together with, for each `a : [0,∞)`, the basic neighborhood
`{∞_E} ∪ ((a,∞) \ E)` of `∞_E` and the basic neighborhood `{∞_D} ∪ ((a,∞) \ D)` of `∞_D`,
where `E = 2ℕ` and `D = 2ℕ+1` sit inside `[0,∞)` via the natural inclusion `ℕ ↪ ℝ`. -/

/-- Modified telophase topology (pi-Base S192): the nonnegative reals `[0,∞)`, together with
two extra points `∞_E = Sum.inr false` and `∞_D = Sum.inr true`. -/
def S192 : Type := ↥(Set.Ici (0 : ℝ)) ⊕ Bool

/-- The even naturals `E = 2ℕ`, viewed inside `[0,∞)`. -/
def S192.E : Set ↥(Set.Ici (0 : ℝ)) := {x | ∃ n : ℕ, (x : ℝ) = 2 * n}

/-- The odd naturals `D = 2ℕ+1`, viewed inside `[0,∞)`. -/
def S192.D : Set ↥(Set.Ici (0 : ℝ)) := {x | ∃ n : ℕ, (x : ℝ) = 2 * n + 1}

/-- The generating sets for the topology on `S192`: order-open rays among the points of
`[0,∞)`, the basic neighborhoods `{∞_E} ∪ ((a,∞) \ E)` of `∞_E`, and the basic
neighborhoods `{∞_D} ∪ ((a,∞) \ D)` of `∞_D`. -/
def S192Generators : Set (Set S192) :=
  (Set.range fun x : ↥(Set.Ici (0 : ℝ)) => Sum.inl '' Set.Iio x) ∪
  (Set.range fun x : ↥(Set.Ici (0 : ℝ)) => Sum.inl '' Set.Ioi x) ∪
  (Set.range fun a : ↥(Set.Ici (0 : ℝ)) =>
    (Sum.inl '' (Set.Ioi a \ S192.E)) ∪ {Sum.inr false}) ∪
  (Set.range fun a : ↥(Set.Ici (0 : ℝ)) =>
    (Sum.inl '' (Set.Ioi a \ S192.D)) ∪ {Sum.inr true})

instance : TopologicalSpace S192 := TopologicalSpace.generateFrom S192Generators

end S192
end PiBase.Spaces
