module

public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.MetricSpace.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S134

/- Space 134: Radial metric on the plane.
See https://topology.pi-base.org/spaces/S000134.
Carrier ℝ², with the radial (a.k.a. Paris) metric r: r(x,y) is the Euclidean distance
d_e(x,y) when x, y are collinear with the origin, and d_e(x,0) + d_e(y,0) otherwise;
the topology is the one generated by the open r-balls. -/

/-- The radial (Paris) metric on ℝ²: Euclidean distance along a common line through
the origin, and the sum of the distances to the origin otherwise. -/
noncomputable def radialDist (x y : EuclideanSpace ℝ (Fin 2)) : ℝ :=
  open Classical in
  if Collinear ℝ ({0, x, y} : Set (EuclideanSpace ℝ (Fin 2))) then
    dist x y
  else
    dist x 0 + dist y 0

/-- The open `radialDist`-balls, taken as a basis for the radial-metric topology. -/
def radialBalls : Set (Set (EuclideanSpace ℝ (Fin 2))) :=
  {s | ∃ (x : EuclideanSpace ℝ (Fin 2)) (ε : ℝ), s = {y | radialDist x y < ε}}

/-- The plane ℝ² (pi-Base S134), with the topology generated by the radial metric. -/
def S134 : Type := EuclideanSpace ℝ (Fin 2)

instance : TopologicalSpace S134 :=
  TopologicalSpace.generateFrom (α := EuclideanSpace ℝ (Fin 2)) radialBalls

end S134
end PiBase.Spaces
