module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Data.Prod.Lex
public import Mathlib.Topology.Order.Basic
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S40

/- Space 40: Altered long ray.
See https://topology.pi-base.org/spaces/S000040.
X = Y ∪ {∞}, where Y = ω₁ × [0,1) carries the lexicographic order topology (an open copy of
the long ray, S38), and a basic neighbourhood of ∞ is Uₐ = {∞} ∪ ((ω₁ \ a) × (0,1)) for each
a < ω₁ — note the (0,1), not [0,1): the left endpoints {(b,0)} of each unit interval are
deliberately excluded from every neighbourhood of ∞, which is what "alters" the plain long
line. The topology is generated by the order-open subbasis on Y together with these Uₐ. -/

/-- The long ray `Y = ω₁ × [0,1)` with its lexicographic order, as used inside the altered
long ray (pi-Base S40).
(`Ordinal.{0} : Type 1`, so the carrier lives in `Type 1`, not `Type 0`.) -/
def S40Ray : Type 1 := { o : Ordinal.{0} // o < ω₁ } ×ₗ ↥(Set.Ico (0 : ℝ) 1)

noncomputable instance : LinearOrder S40Ray :=
  inferInstanceAs (LinearOrder ({o : Ordinal.{0} // o < ω₁} ×ₗ ↥(Set.Ico (0 : ℝ) 1)))

/-- The Altered long ray (pi-Base S40): the long ray `Y` with one extra point `∞ = none`
adjoined, whose basic neighbourhoods are `{∞} ∪ ((ω₁ \ a) × (0,1))` for `a < ω₁`. -/
def S40 : Type 1 := Option S40Ray

/-- The subbasis generating the topology on `S40`: the order-open rays of `Y` (lifted through
`some`, giving `Y` its usual lexicographic order topology as an open subspace), together with
the altered neighbourhoods `Uₐ = {∞} ∪ ((ω₁ \ a) × (0,1))` of `∞` for each ordinal `a < ω₁`. -/
def S40.subbasis : Set (Set S40) :=
  { s | ∃ a : S40Ray, s = some '' { b : S40Ray | a < b } ∨ s = some '' { b : S40Ray | b < a } } ∪
  { s | ∃ a : { o : Ordinal.{0} // o < ω₁ },
      s = insert none (some '' { p : S40Ray | a.1 ≤ (ofLex p).1.1 ∧ 0 < ((ofLex p).2 : ℝ) }) }

instance : TopologicalSpace S40 := TopologicalSpace.generateFrom S40.subbasis

end S40
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S40 as a bundled `Space` (carrier + topology). -/
noncomputable def S40 : Space := ⟨PiBase.Spaces.S40.S40, inferInstance⟩

end PiBase.Formal
