module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S211

/- Space 211: Join of cofinite and modified right "closed-ray" topologies on ω₁+1.
See https://topology.pi-base.org/spaces/S000211.
The set X = ω₁+1 (the ordinals up to and including the least uncountable ordinal ω₁),
with the topology generated by the base `[α,ω₁] \ F = {x | α ≤ x} \ F` for `α < ω₁` and
`F ⊆ X` finite — the join, in the lattice of topologies, of the cofinite topology and the
topology with base the closed rays `[α,ω₁]` for `α < ω₁` (but not `α = ω₁`). -/

/-- Join of cofinite and modified right "closed-ray" topologies on ω₁+1 (pi-Base S211):
the ordinals up to and including the least uncountable ordinal ω₁. -/
def S211 : Type 1 := {o : Ordinal.{0} // o ≤ ω₁}

noncomputable instance : LinearOrder S211 :=
  inferInstanceAs (LinearOrder {o : Ordinal.{0} // o ≤ ω₁})

instance S211_top : TopologicalSpace S211 :=
  TopologicalSpace.generateFrom
    {s : Set S211 | ∃ (a : S211) (F : Finset S211), s = {x : S211 | a ≤ x} \ ↑F}

end S211
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S211 as a bundled `Space` (carrier + topology). -/
noncomputable def S211 : Space := ⟨PiBase.Spaces.S211.S211, PiBase.Spaces.S211.S211_top⟩

end PiBase.Formal
