module

public import Mathlib.Data.Nat.Prime.Nth
public import Mathlib.Topology.Instances.Rat
public import Mathlib.Topology.Defs.Induced

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S124

/- Space 124: Roy's lattice subspace.
See https://topology.pi-base.org/spaces/S000124.
Let `p i` be the `i`-th prime, and `C i` the rationals `a / (p i)^n` with `a : ℤ`
not divisible by `p i` (a dense subset of ℚ). The carrier is
`X = {(r, i) : ℚ × ℕ // r ∈ C i}`, i.e. Roy's lattice space (π-Base S123) with its
point at infinity `ω` removed. Basic neighborhoods of `(r, 2n)` are the "rows"
`Uₑ(r,2n) = {(t,2n) : |r-t|<ε}`; basic neighborhoods of `(r,2n-1)` are the
"lattice" sets `Vₑ(r,2n-1) = {(t,m) : |r-t|<ε, |m-n|≤1}`. -/

/-- The `i`-th prime. -/
noncomputable def S124.p (i : ℕ) : ℕ := Nat.nth Nat.Prime i

/-- The dense subset of ℚ attached to index `i`: rationals `a / (p i)^n` with
`a : ℤ` not divisible by the `i`-th prime `p i`. -/
noncomputable def S124.C (i : ℕ) : Set ℚ :=
  {r : ℚ | ∃ (n : ℕ) (a : ℤ), ¬ (S124.p i : ℤ) ∣ a ∧ r = (a : ℚ) / (S124.p i : ℚ) ^ n}

/-- Roy's lattice subspace (pi-Base S124): Roy's lattice space (S123) with its
point at infinity removed, i.e. the set of pairs `(r, i) : ℚ × ℕ` with `r ∈ C i`. -/
noncomputable def S124 : Type := {x : ℚ × ℕ // x.1 ∈ S124.C x.2}

namespace S124

/-- The basic "row" neighborhood of `(r, 2n)`: all `(t, 2n)` with `t` within `ε` of `r`. -/
def U (r : ℚ) (n : ℕ) (ε : ℚ) : Set (ℚ × ℕ) :=
  {x : ℚ × ℕ | x.2 = 2 * n ∧ |r - x.1| < ε}

/-- The basic "lattice" neighborhood of `(r, 2n-1)`: all `(t, m)` with `t` within
`ε` of `r` and `m` within `1` of `n`. -/
def V (r : ℚ) (n : ℕ) (ε : ℚ) : Set (ℚ × ℕ) :=
  {x : ℚ × ℕ | |(x.2 : ℤ) - (n : ℤ)| ≤ 1 ∧ |r - x.1| < ε}

/-- The topology on `ℚ × ℕ` generated by the basic row and lattice neighborhoods. -/
@[reducible] def ambientTopology : TopologicalSpace (ℚ × ℕ) :=
  TopologicalSpace.generateFrom
    ({s | ∃ r n ε, s = U r n ε} ∪ {s | ∃ r n ε, s = V r n ε})

noncomputable instance S124_top : TopologicalSpace S124 :=
  @instTopologicalSpaceSubtype (ℚ × ℕ) (fun x => x.1 ∈ S124.C x.2) ambientTopology

end S124

end S124
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S124 as a bundled `Space` (carrier + topology). -/
noncomputable def S124 : Space := ⟨PiBase.Spaces.S124.S124, PiBase.Spaces.S124.S124.S124_top⟩

end PiBase.Formal
