module

public import PiBaseLean.Spaces.S91.Defs
public import Mathlib.Topology.Constructions

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S92

/- Space 92: Thomas corkscrew.
See https://topology.pi-base.org/spaces/S000092.
The double-sided Jones machine `DJ(Y, H, K)` applied to `Y = S91` (the Thomas plank) and
its two inseparable closed subsets `H = L₀` (the ground row, second coordinate `0`) and
`K` (the row-endpoints, first coordinate `0`): take `Z = (Y × ℤ) ⊕ {p⁻, p⁺}` with the
topology generated by the basic opens `U ×ˢ {n}` (for `U` open in `Y`, `n : ℤ`) together
with the tail neighbourhoods `{p⁺} ∪ Y ×ˢ {n // n ≥ N}` and `{p⁻} ∪ Y ×ˢ {n // n ≤ -N}`
of the two new limit points, then quotient by gluing `(x, 2n) ~ (x, 2n+1)` for `x ∈ H` and
`(x, 2n-1) ~ (x, 2n)` for `x ∈ K` — alternately stitching consecutive copies of `Y` together
along `H` or `K` — carrying the quotient topology. -/

/-- The ground row `H = L₀` of the Thomas plank `Y = S91`: points whose second coordinate
is `0`. Together with `K`, these are the two closed subsets of `Y` that cannot be
separated by disjoint open sets. -/
def S92.H (x : S91) : Prop := x.val.2 = 0

/-- The row-endpoints `K = {(0, 1/n) : n ∈ ℕ}` of the Thomas plank `Y = S91`: points whose
first coordinate is `0`. Together with `H`, these are the two closed subsets of `Y` that
cannot be separated by disjoint open sets. -/
def S92.K (x : S91) : Prop := x.val.1 = 0

/-- The pre-quotient space `Z = (Y × ℤ) ⊕ Bool`: a two-sided sequence of copies of the
Thomas plank `Y = S91`, indexed by `ℤ`, plus two extra points `p⁻ = inr false` and
`p⁺ = inr true`. -/
def S92.PreZ : Type := (S91 × ℤ) ⊕ Bool

/-- The gluing relation on `S92.PreZ` underlying the double-sided Jones machine: reflexive
everywhere, and additionally identifying `(x, 2n)` with `(x, 2n+1)` for `x ∈ H`, and
`(x, 2n-1)` with `(x, 2n)` for `x ∈ K`, for every copy-index `n : ℤ`. Each point of
`Y × ℤ` is glued to at most one other point (since `H` and `K` are disjoint, a point of
`Y` lies in at most one of them), so this relation is already transitive. -/
def S92.glue : S92.PreZ → S92.PreZ → Prop
  | .inl (x, m), .inl (x', m') =>
      x = x' ∧ ((m = m') ∨
        (S92.H x ∧ ∃ n : ℤ, (m = 2 * n ∧ m' = 2 * n + 1) ∨ (m = 2 * n + 1 ∧ m' = 2 * n)) ∨
        (S92.K x ∧ ∃ n : ℤ, (m = 2 * n - 1 ∧ m' = 2 * n) ∨ (m = 2 * n ∧ m' = 2 * n - 1)))
  | .inr b, .inr b' => b = b'
  | .inl _, .inr _ => False
  | .inr _, .inl _ => False

theorem S92.glue_refl : ∀ a, S92.glue a a := by
  rintro (⟨x, m⟩ | b)
  · exact ⟨rfl, Or.inl rfl⟩
  · rfl

theorem S92.glue_symm : ∀ a b, S92.glue a b → S92.glue b a := by
  rintro (⟨x, m⟩ | b) (⟨x', m'⟩ | b') h
  · obtain ⟨rfl, h⟩ := h
    refine ⟨rfl, ?_⟩
    rcases h with h | ⟨hx, n, h | h⟩ | ⟨hx, n, h | h⟩
    · exact Or.inl h.symm
    · exact Or.inr (Or.inl ⟨hx, n, Or.inr h.symm⟩)
    · exact Or.inr (Or.inl ⟨hx, n, Or.inl h.symm⟩)
    · exact Or.inr (Or.inr ⟨hx, n, Or.inr h.symm⟩)
    · exact Or.inr (Or.inr ⟨hx, n, Or.inl h.symm⟩)
  · cases h
  · cases h
  · cases h; rfl

/-- A point `x ∈ Y` cannot lie in both edges `H` and `K`: `H` forces the second coordinate
to be `0`, in which case the carrier's defining disjunction puts the first coordinate in
`(0, 1)`, so it cannot also be `0` as `K` would require. -/
theorem S92.not_H_and_K (x : S91) : ¬ (S92.H x ∧ S92.K x) := by
  rintro ⟨hH, hK⟩
  unfold S92.H at hH
  unfold S92.K at hK
  rcases x.property with ⟨-, hx1⟩ | ⟨n, hx2, -⟩
  · exact absurd hK (ne_of_gt hx1.1)
  · have hn1 : (0 : ℝ) < (n : ℝ) + 1 :=
      lt_of_lt_of_le zero_lt_one (le_add_of_nonneg_left (Nat.cast_nonneg n))
    have hpos : (0 : ℝ) < 1 / ((n : ℝ) + 1) := div_pos one_pos hn1
    rw [hx2] at hH
    exact absurd hH (ne_of_gt hpos)

theorem S92.glue_trans : ∀ a b c, S92.glue a b → S92.glue b c → S92.glue a c := by
  rintro (⟨x, m⟩ | b) (⟨x', m'⟩ | b') (⟨x'', m''⟩ | b'') hab hbc
  · obtain ⟨rfl, hab⟩ := hab
    obtain ⟨rfl, hbc⟩ := hbc
    refine ⟨rfl, ?_⟩
    -- `x` lies in at most one of `H`, `K` (`not_H_and_K`), so a cross `H`-then-`K` (or
    -- `K`-then-`H`) step is impossible. A same-kind composition (`H`-then-`H`, or
    -- `K`-then-`K`) always collapses to the reflexive case: each of `H`, `K` pairs up `m`
    -- with its partner via a fixed-parity involution, so composing it with itself forces
    -- `m = m''`, i.e. `a` and `c` are in fact the same point.
    rcases hab with hab | ⟨hxH, n, hab⟩ | ⟨hxK, n, hab⟩
    · exact hab ▸ hbc
    · rcases hbc with hbc | ⟨_, n', hbc⟩ | ⟨hxK, _, hbc⟩
      · exact hbc ▸ (Or.inr (Or.inl ⟨hxH, n, hab⟩))
      · refine Or.inl ?_
        rcases hab with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
          rcases hbc with ⟨h1, h2⟩ | ⟨h1, h2⟩ <;> omega
      · exact absurd ⟨hxH, hxK⟩ (S92.not_H_and_K x)
    · rcases hbc with hbc | ⟨hxH, _, hbc⟩ | ⟨_, n', hbc⟩
      · exact hbc ▸ (Or.inr (Or.inr ⟨hxK, n, hab⟩))
      · exact absurd ⟨hxH, hxK⟩ (S92.not_H_and_K x)
      · refine Or.inl ?_
        rcases hab with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
          rcases hbc with ⟨h1, h2⟩ | ⟨h1, h2⟩ <;> omega
  · cases hbc
  · cases hab
  · cases hab
  · cases hab
  · cases hbc
  · cases hbc
  · cases hab; cases hbc; rfl

instance S92.setoid : Setoid S92.PreZ where
  r := S92.glue
  iseqv := ⟨S92.glue_refl, fun {a b} => S92.glue_symm a b, fun {a b c} => S92.glue_trans a b c⟩

/-- The basic opens of `Z` coming from the product topology on `Y × ℤ` (with `ℤ` discrete):
a slice `U ×ˢ {n}` for `U` open in `Y` and `n : ℤ`. -/
def S92.prodBasic (U : Set S91) (n : ℤ) : Set S92.PreZ :=
  Sum.inl '' (U ×ˢ ({n} : Set ℤ))

/-- The tail neighbourhoods of the new limit point `p⁺ = inr true`: the point itself
together with every later copy `Y × {n // n ≥ N}`. -/
def S92.tailPos (N : ℤ) : Set S92.PreZ :=
  {Sum.inr true} ∪ Sum.inl '' ((Set.univ : Set S91) ×ˢ {n : ℤ | N ≤ n})

/-- The tail neighbourhoods of the new limit point `p⁻ = inr false`: the point itself
together with every earlier copy `Y × {n // n ≤ -N}`. -/
def S92.tailNeg (N : ℤ) : Set S92.PreZ :=
  {Sum.inr false} ∪ Sum.inl '' ((Set.univ : Set S91) ×ˢ {n : ℤ | n ≤ -N})

/-- The topology on `Z`, generated by the product-slice basic opens together with the tail
neighbourhoods of the two new limit points `p⁻, p⁺`. A set `U ⊆ Z` is a union of finite
intersections of these generators iff `U ∩ (Y × ℤ)` is open in the product topology (`ℤ`
discrete) and, whenever `U` contains `p⁺` (resp. `p⁻`), it contains some tail `Y × {n ≥ N}`
(resp. `Y × {n ≤ -N}`) — matching the π-Base description exactly. -/
instance S92.instTopologicalSpacePreZ : TopologicalSpace S92.PreZ :=
  TopologicalSpace.generateFrom
    ({s | ∃ U : Set S91, ∃ n : ℤ, IsOpen U ∧ s = S92.prodBasic U n} ∪
      {s | ∃ N : ℤ, s = S92.tailPos N} ∪
      {s | ∃ N : ℤ, s = S92.tailNeg N})

/-- Thomas corkscrew (pi-Base S92): the double-sided Jones machine applied to the Thomas
plank `Y = S91` and its two inseparable closed subsets `H, K`, realized as the quotient
`Z / ~` of the pre-quotient space `Z = (Y × ℤ) ⊕ Bool` by the gluing relation `S92.glue`. -/
def S92 : Type := Quotient S92.setoid

instance : TopologicalSpace S92 := instTopologicalSpaceQuotient

end S92
end PiBase.Spaces
