module

public import Mathlib.Analysis.InnerProductSpace.PiL2

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S74

/- Space 74: Niemytzki plane.
See https://topology.pi-base.org/spaces/S000074.
Carrier: the closed upper half plane `{(x, y) ∈ ℝ² : y ≥ 0}`. Topology: generated by
ordinary Euclidean balls (restricted to the half plane) together with, at each boundary
point `(x₀, 0)`, the sets `{(x₀, 0)} ∪ D` for `D` an open disk in the upper half plane
tangent to the x-axis at `(x₀, 0)` — i.e. the ball of radius `r` centered at `(x₀, r)`. -/

/-- The closed upper half plane `{(x, y) ∈ ℝ² : y ≥ 0}`, carrier of the Niemytzki plane
(pi-Base S74). -/
def S74 : Type := {p : EuclideanSpace ℝ (Fin 2) // 0 ≤ p 1}

/-- The Niemytzki (tangent disc) topology: generated by Euclidean balls restricted to the
half plane, together with the tangent-disc neighborhoods `{(x₀, 0)} ∪ ball (x₀, r) r` at each
boundary point `(x₀, 0)`. -/
instance : TopologicalSpace S74 :=
  TopologicalSpace.generateFrom
    ({ S : Set S74 | ∃ (c : EuclideanSpace ℝ (Fin 2)) (r : ℝ),
        S = Subtype.val ⁻¹' Metric.ball c r } ∪
     { S : Set S74 | ∃ (x₀ r : ℝ), 0 < r ∧
        S = {z : S74 | z.val = !₂[x₀, 0]} ∪ Subtype.val ⁻¹' Metric.ball !₂[x₀, r] r })

end S74
end PiBase.Spaces
