module

public import Mathlib.Topology.Order
public import Mathlib.Data.Sum.Order
public import Mathlib.Data.ENat.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S167

/- Space 167: Right "open-ray" topology on ω+1+ω*.
See https://topology.pi-base.org/spaces/S000167.
The carrier is the linear sum, in order, of ω+1 (ℕ with a top point adjoined) followed by
ω* (ℕ with the reversed order); the topology is generated by X itself together with the
upper rays (a, →) for a ∈ X. -/

/-- Right "open-ray" topology on `ω+1+ω*` (pi-Base S167): the carrier is `ω+1` (i.e.
`ℕ∞ = WithTop ℕ`) concatenated with `ω*` (i.e. `ℕᵒᵈ`), and the open sets are exactly `X`
and the upper rays `(a, →)` for `a ∈ X`. -/
def S167 : Type := ℕ∞ ⊕ₗ ℕᵒᵈ

instance : LinearOrder S167 := inferInstanceAs (LinearOrder (ℕ∞ ⊕ₗ ℕᵒᵈ))

instance : TopologicalSpace S167 :=
  TopologicalSpace.generateFrom
    ({Set.univ} ∪ {U : Set S167 | ∃ a : S167, U = Set.Ioi a})

end S167
end PiBase.Spaces
