module

public import Mathlib.SetTheory.Cardinal.Cofinality
public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Defs.Induced
public import Mathlib.Topology.Order.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Cardinal

namespace PiBase.Spaces
namespace S208

/- Space 208: Hewitt realcompactification of Rudin's Dowker space.
See https://topology.pi-base.org/spaces/S000208.
The subspace of the box-topology product ∏ₙ (ω_{n+1}+1) consisting of those `f` with
ω < cf(f n) for every `n`. -/

/-- The `n`-th factor: the ordinal `ω_{n+1} + 1`, realized as the set of ordinals
`≤ ω_{n+1}` (i.e. `Set.Iic (ω_ (n+1))`). Ordinals live in `Type (u+1)`, so this factor
is in `Type 1`. -/
def S208.Factor (n : ℕ) : Type 1 := { x : Ordinal.{0} // x ∈ Set.Iic (Ordinal.omega (n + 1)) }

noncomputable instance (n : ℕ) : LinearOrder (S208.Factor n) :=
  inferInstanceAs (LinearOrder { x : Ordinal.{0} // x ∈ Set.Iic (Ordinal.omega (n + 1)) })

noncomputable instance (n : ℕ) : TopologicalSpace (S208.Factor n) := Preorder.topology (S208.Factor n)

/-- The carrier: those `f ∈ ∏ₙ (ω_{n+1}+1)` such that `ω < cf(f n)` for all `n`. -/
def S208 : Type 1 :=
  { f : ∀ n, S208.Factor n // ∀ n, ℵ₀ < Ordinal.cof (f n).1 }

/-- The box topology on the ambient product `∏ₙ (ω_{n+1}+1)`, generated by boxes
`∏ₙ Uₙ` where each `Uₙ` is open in the `n`-th factor, restricted to `S208`. -/
noncomputable instance S208_top : TopologicalSpace S208 :=
  TopologicalSpace.induced (Subtype.val : S208 → ∀ n, S208.Factor n)
    (TopologicalSpace.generateFrom
      { S | ∃ U : ∀ n, Set (S208.Factor n), (∀ n, IsOpen (U n)) ∧ S = Set.univ.pi U })

end S208
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S208 as a bundled `Space` (carrier + topology). -/
noncomputable def S208 : Space := ⟨PiBase.Spaces.S208.S208, PiBase.Spaces.S208.S208_top⟩

end PiBase.Formal
