module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S199

/- Space 199: Left ray topology on $\omega$.
See https://topology.pi-base.org/spaces/S000199.
Carrier `ω = ℕ`; the open sets are generated by the left rays
`(←, n] = {0, 1, ..., n}` for `n < ω` (together with `∅` and `ω` itself). -/

/-- Left ray topology on `ω` (pi-Base S199). -/
def S199 : Type := ℕ

instance : TopologicalSpace S199 :=
  TopologicalSpace.generateFrom {s : Set S199 | ∃ n : ℕ, s = Set.Iic n}

end S199
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S199 as a bundled `Space` (carrier + topology). -/
noncomputable def S199 : Space := ⟨PiBase.Spaces.S199.S199, inferInstance⟩

end PiBase.Formal
