module

public import Mathlib.Topology.Compactification.OnePoint.Basic
public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic

@[expose] public section

open Topology OnePoint

namespace PiBase.Spaces
namespace S154

/- Space 154: Fort space on the real numbers.
See https://topology.pi-base.org/spaces/S000154.
Carrier `X = ℝ ∪ {∞}` (realized as `OnePoint ℝ`); every point of `ℝ` is isolated and the
open neighborhoods of `∞` are exactly the cofinite subsets of `X` containing it — i.e. the
topology is generated by the singletons `{x}`, `x : ℝ`, together with the cofinite sets
containing `∞`. -/

/-- Fort space on the real numbers (pi-Base S154), carrier `ℝ ∪ {∞}`. -/
def S154 : Type := OnePoint ℝ

/-- The topology generated by the singletons of real points (making them isolated)
together with the cofinite sets containing `∞` (making these exactly the
neighborhoods of `∞`). -/
instance : TopologicalSpace S154 :=
  TopologicalSpace.generateFrom
    ({s : Set (OnePoint ℝ) | ∃ x : ℝ, s = {(x : OnePoint ℝ)}} ∪
      {s : Set (OnePoint ℝ) | (∞ : OnePoint ℝ) ∈ s ∧ sᶜ.Finite})

end S154
end PiBase.Spaces
