module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S100

/- Space 100: David Gao's ultraconnected non-contractible space.
See https://topology.pi-base.org/spaces/S000100.
The carrier is the set of partial functions `f : ℤ →. Bool` whose domain is some
`Set.Iic n` (n is the "length" `l(f)`), which are eventually `false` towards `-∞`,
and which either are identically `false` with `l(f) ≤ 0`, or have a *last* index
`n₀ < 0` with `f(n₀) = true` and `l(f) ≤ -n₀`. The topology is generated by the
subbasis of complements of the principal down-sets `T_x = {y : y ≤ x}` (for the
truncation order) together with the complements of the "length" sets
`K_n = {y : l(y) ≤ n}`. -/

namespace S100

/-- A raw candidate element of `X`: a length `n : ℤ` together with a function on its
"domain" `Set.Iic n`, recording `f` as a genuine partial function (no junk values
outside the domain). -/
structure Raw where
  /-- The length `l(f)` of the partial function, i.e. its domain is `Set.Iic n`. -/
  n : ℤ
  /-- The values of the partial function on its domain `Set.Iic n`. -/
  f : Set.Iic n → Bool

/-- Condition 2: `f` is eventually `false` towards `-∞`, i.e. there is some `m` below
which every value of `f` (on its domain) is `false`. -/
def Raw.EventuallyFalse (x : Raw) : Prop :=
  ∃ m : ℤ, ∀ k : Set.Iic x.n, (k : ℤ) ≤ m → x.f k = false

/-- Condition 3: either `f` is identically `false` on its domain and `l(f) ≤ 0`; or
there is a *last* negative index `n₀` in the domain (i.e. `n₀ < 0`, `n₀ ≤ l(f)`,
`f n₀ = true`, and `f m = false` for every `m < n₀`) with `l(f) ≤ -n₀`. -/
def Raw.LastNegativeOne (x : Raw) : Prop :=
  (∀ k : Set.Iic x.n, x.f k = false) ∧ x.n ≤ 0
  ∨ ∃ n₀ : ℤ, ∃ (_hn₀ : n₀ < 0) (hle : n₀ ≤ x.n), x.f ⟨n₀, hle⟩ = true
      ∧ (∀ m : ℤ, ∀ hm : m ≤ x.n, m < n₀ → x.f ⟨m, hm⟩ = false)
      ∧ x.n ≤ -n₀

end S100

/-- The underlying set `X` of David Gao's ultraconnected non-contractible space
(pi-Base S100): partial functions `f : ℤ →. Bool` with domain `Set.Iic (l f)`,
eventually `false` towards `-∞`, and satisfying `S100.Raw.LastNegativeOne`. -/
def S100 : Type := {x : S100.Raw // x.EventuallyFalse ∧ x.LastNegativeOne}

namespace S100

/-- The length `l(x)` of `x ∈ X`: the `n` such that `x`'s domain is `Set.Iic n`. -/
def length (x : S100) : ℤ := x.1.n

/-- The *truncation* order on `X`: `g ≤ f` iff `g` is the restriction of `f` to some
initial segment `Set.Iic n` of `f`'s own domain, i.e. `g` has length `n ≤ l(f)` and
agrees with `f` on all of `g`'s domain. -/
def truncation (g f : S100) : Prop :=
  ∃ h : g.1.n ≤ f.1.n, ∀ k : Set.Iic g.1.n,
    g.1.f k = f.1.f ⟨(k : ℤ), (k.2.trans h)⟩

/-- The principal down-set `T_x = {y ∈ X : y ≤ x}` for the truncation order. -/
def T (x : S100) : Set S100 := {y : S100 | truncation y x}

/-- The "length" set `K_n = {y ∈ X : l(y) ≤ n}`. -/
def K (n : ℤ) : Set S100 := {y : S100 | length y ≤ n}

/-- The closed subbasis `{T_x : x ∈ X} ∪ {K_n : n ∈ ℤ}`. -/
def closedSubbasis : Set (Set S100) := (Set.range T) ∪ (Set.range K)

/-- The open subbasis generating the topology on `X`: complements of the sets in
`closedSubbasis`. -/
def subbasis : Set (Set S100) := compl '' closedSubbasis

end S100

instance S100_top : TopologicalSpace S100 := TopologicalSpace.generateFrom S100.subbasis

end S100
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S100 as a bundled `Space` (carrier + topology). -/
noncomputable def S100 : Space := ⟨PiBase.Spaces.S100.S100, PiBase.Spaces.S100.S100_top⟩

end PiBase.Formal
