module

public import Mathlib.Topology.Order.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S150

/- Space 150: Right "closed-ray" topology on $[0,1]\cap\mathbb Q$.
See https://topology.pi-base.org/spaces/S000150.
The carrier is $X = [0,1]\cap\mathbb Q$ (as a subtype of ℚ); the topology is generated by
the base of closed rays $[x,\to) = \{y \in X \mid x \le y\}$ for $x \in X$. -/

/-- Right "closed-ray" topology on $[0,1]\cap\mathbb Q$ (pi-Base S150). -/
def S150 : Type := ↥(Set.Icc (0 : ℚ) 1)

instance : Preorder S150 := Subtype.preorder _

instance : TopologicalSpace S150 :=
  TopologicalSpace.generateFrom {s | ∃ x : S150, s = Set.Ici x}

end S150
end PiBase.Spaces
