module

public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S62

/- Space 62: Discrete rational extension of ℝ.
See https://topology.pi-base.org/spaces/S000062.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
all singletons `{x}` for `x ∈ ℚ` — finer than the indiscrete rational extension (S58). -/

/-- Discrete rational extension of ℝ (pi-Base S62). -/
def S62 : Type := ℝ

instance : TopologicalSpace S62 :=
  TopologicalSpace.generateFrom
    ({ U : Set ℝ | IsOpen U } ∪ { s : Set ℝ | ∃ x : ℚ, s = {(x : ℝ)} })

end S62
end PiBase.Spaces
