module

public import Mathlib.Topology.Basic
public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Data.Set.Finite.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S99

/- Space 99: Alexandroff square.
See https://topology.pi-base.org/spaces/S000099.
Carrier `X = [0,1] × [0,1] ⊆ ℝ²`. For an off-diagonal point `(x, y)` (`x ≠ y`),
basic neighborhoods are the vertical segments `{x} × (y - ε, y + ε)`, `ε > 0`.
For a diagonal point `(x, x)`, basic neighborhoods are the sets `S × (x - ε, x + ε)`,
`ε > 0`, where `S` ranges over cofinite subsets of `[0,1]` containing `x`.
The topology is generated by this family of basic neighborhoods. -/

/-- Alexandroff square (pi-Base S99), on the carrier `[0,1] × [0,1] ⊆ ℝ²`. -/
def S99 : Type := ↥(Set.Icc (0 : ℝ) 1) × ↥(Set.Icc (0 : ℝ) 1)

/-- The basic vertical-segment neighborhood of an off-diagonal point `(x, y)`
(`x ≠ y`): all points with the same first coordinate `x` and second coordinate
within `ε` of `y`. -/
def S99.vertNbhd (p : S99) (ε : ℝ) : Set S99 :=
  {q : S99 | q.1 = p.1 ∧ |(q.2.val : ℝ) - p.2.val| < ε}

/-- The basic neighborhood of a diagonal point `(x, x)`: a cofinite-in-first-coordinate
strip `S × (x - ε, x + ε)`, where `S` is the complement (within the carrier) of a finite
set `F` of first coordinates not containing `x`. -/
def S99.diagNbhd (x : ↥(Set.Icc (0 : ℝ) 1)) (F : Set ↥(Set.Icc (0 : ℝ) 1)) (ε : ℝ) : Set S99 :=
  {q : S99 | q.1 ∉ F ∧ |(q.2.val : ℝ) - x.val| < ε}

instance S99_top : TopologicalSpace S99 :=
  TopologicalSpace.generateFrom
    ({s : Set S99 | ∃ p : S99, p.1 ≠ p.2 ∧ ∃ ε > (0 : ℝ), s = S99.vertNbhd p ε} ∪
      {s : Set S99 | ∃ x : ↥(Set.Icc (0 : ℝ) 1), ∃ F : Set ↥(Set.Icc (0 : ℝ) 1), F.Finite ∧
        x ∉ F ∧ ∃ ε > (0 : ℝ), s = S99.diagNbhd x F ε})

end S99
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S99 as a bundled `Space` (carrier + topology). -/
noncomputable def S99 : Space := ⟨PiBase.Spaces.S99.S99, PiBase.Spaces.S99.S99_top⟩

end PiBase.Formal
