module

public import Mathlib.Topology.Order
public import Mathlib.Data.PNat.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S5

/- Space 5: Odd-Even Topology.
See https://topology.pi-base.org/spaces/S000005.
On `X = ℕ+` (pi-Base's `ℕ` excludes `0`), the topology is generated by the basis
of pairs `{2k-1, 2k}` for `k : ℕ+`. -/

/-- Odd-Even Topology (pi-Base S5). -/
def S5 : Type := ℕ+

instance S5_top : TopologicalSpace S5 :=
  TopologicalSpace.generateFrom {s : Set S5 | ∃ k : ℕ+, s = {2 * k - 1, 2 * k}}

end S5
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S5 as a bundled `Space` (carrier + topology). -/
noncomputable def S5 : Space := ⟨PiBase.Spaces.S5.S5, PiBase.Spaces.S5.S5_top⟩

end PiBase.Formal
