module

public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S42

/- Space 42: Right ray topology on the reals.
See https://topology.pi-base.org/spaces/S000042.
The carrier is ℝ; the topology is generated by the basis of right rays
`B_y = {x : y < x}` (i.e. `Set.Ioi y` for each `y : ℝ`). -/

/-- Right ray topology on the reals (pi-Base S42). -/
def S42 : Type := ℝ

instance : TopologicalSpace S42 :=
  TopologicalSpace.generateFrom {s : Set ℝ | ∃ y : ℝ, s = Set.Ioi y}

end S42
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S42 as a bundled `Space` (carrier + topology). -/
noncomputable def S42 : Space := ⟨PiBase.Spaces.S42.S42, inferInstance⟩

end PiBase.Formal
