module

public import PiBaseLean.Spaces.S79.Defs
public import Mathlib.Logic.Relation

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S89

/- Space 89: Deleted Tychonoff corkscrew.
See https://topology.pi-base.org/spaces/S000089.
The subspace `DJ(Y, H, K) \ {a⁻}` of the Tychonoff corkscrew, where `Y` is the deleted
Tychonoff plank (S79) and `H, K ⊆ Y` are its two "edges" (the top edge `[0,ω₁] × {ω}`
and the right edge `{ω₁} × [0,ω]`, corner point excluded) that cannot be separated by
open sets in `Y`. The Tychonoff corkscrew `DJ(Y,H,K)` (pi-Base S88) is not formalized
as its own file here, so the whole construction — a bi-infinite chain of copies of `Y`
glued alternately along `H` and along `K`, plus two limit points `p⁻, p⁺` — is built
inline below, and then the point `a⁻` (the class of `p⁻`) is deleted to give S89. -/

namespace S89

/-- The "top edge" `H = [0,ω₁] × {ω}` of the deleted Tychonoff plank `Y = S79`
(the corner point is already excluded from `S79`). -/
def H : Set S79 := {p | p.1.2 = OnePoint.infty}

/-- The "right edge" `K = {ω₁} × [0,ω]` of the deleted Tychonoff plank `Y = S79`
(the corner point is already excluded from `S79`). -/
def K : Set S79 := {p | p.1.1 = (⟨ω₁, le_refl ω₁⟩ : S78.Fst)}

/-- The carrier of `Z = (Y × ℤ) ∪ {p⁻, p⁺}` before quotienting: a copy of `Y` for
every integer, plus two extra points `p⁻ = inr false` and `p⁺ = inr true`. -/
def Z : Type 1 := (S79 × ℤ) ⊕ Bool

/-- The extra point `p⁺` of `Z`. -/
def Z.pPos : Z := Sum.inr true

/-- The extra point `p⁻` of `Z`. -/
def Z.pNeg : Z := Sum.inr false

/-- Subbasis for the topology on `Z`. Three kinds of generating sets:
`Sum.inl '' (V ×ˢ {n})` for `V` open in `Y` and `n : ℤ` (giving the product topology
with `ℤ` discrete on `Y × ℤ`); a "tail" neighborhood `{p⁺} ∪ Y × {n : n ≥ N}` of `p⁺`
for each `N : ℕ`; and a "tail" neighborhood `{p⁻} ∪ Y × {n : n ≤ -N}` of `p⁻` for each
`N : ℕ`. Generating the topology from these reproduces exactly the rule from pi-Base:
`U` is open iff `U ∩ (Y × ℤ)` is open in the product topology, and (if `U` contains
`p⁺`, resp. `p⁻`) `U` contains a tail of `Y`-copies. -/
def Z.subbasis : Set (Set Z) :=
  (Set.range fun (q : {V : Set S79 // IsOpen V} × ℤ) =>
      Sum.inl '' (q.1.1 ×ˢ ({q.2} : Set ℤ)))
  ∪ (Set.range fun N : ℕ =>
      insert Z.pPos (Sum.inl '' ((Set.univ : Set S79) ×ˢ {n : ℤ | (N : ℤ) ≤ n})))
  ∪ (Set.range fun N : ℕ =>
      insert Z.pNeg (Sum.inl '' ((Set.univ : Set S79) ×ˢ {n : ℤ | n ≤ -(N : ℤ)})))

instance : TopologicalSpace Z := TopologicalSpace.generateFrom Z.subbasis

/-- The gluing relation on `Z`: `(y, 2n) ~ (y, 2n+1)` for `y ∈ H`, and
`(y, 2n-1) ~ (y, 2n)` for `y ∈ K`, no other relations between distinct points (the
`Setoid` below takes the equivalence closure of this base relation). -/
inductive GlueRel : Z → Z → Prop
  | ofH (y : S79) (n : ℤ) (hy : y ∈ H) :
      GlueRel (Sum.inl (y, 2 * n)) (Sum.inl (y, 2 * n + 1))
  | ofK (y : S79) (n : ℤ) (hy : y ∈ K) :
      GlueRel (Sum.inl (y, 2 * n - 1)) (Sum.inl (y, 2 * n))

/-- The equivalence relation on `Z` generated by `GlueRel`, i.e. its reflexive,
symmetric, transitive closure. -/
def gluingSetoid : Setoid Z := Setoid.mk (Relation.EqvGen GlueRel) (Relation.EqvGen.is_equivalence GlueRel)

/-- The Tychonoff corkscrew `DJ(Y,H,K)` (pi-Base S88), realized as the quotient of `Z`
by the gluing relation, carrying the quotient topology. Named `PreQuotient` (rather
than `S88`) since S88 is not formalized as its own file here. -/
def PreQuotient : Type 1 := Quotient gluingSetoid

instance : TopologicalSpace PreQuotient := inferInstanceAs (TopologicalSpace (Quotient gluingSetoid))

/-- The limit point `a⁺ = q(p⁺)` of `DJ(Y,H,K)`, the image of `p⁺` under the quotient
map. -/
def aPos : PreQuotient := Quotient.mk'' Z.pPos

/-- The limit point `a⁻ = q(p⁻)` of `DJ(Y,H,K)`, the image of `p⁻` under the quotient
map. This is the point deleted to form S89. -/
def aNeg : PreQuotient := Quotient.mk'' Z.pNeg

end S89

/-- Deleted Tychonoff corkscrew (pi-Base S89): the Tychonoff corkscrew `DJ(Y,H,K)`
with its limit point `a⁻` removed, as a subtype with the subspace topology. -/
def S89 : Type 1 := {x : S89.PreQuotient // x ≠ S89.aNeg}

instance : TopologicalSpace S89 := inferInstanceAs (TopologicalSpace {x : S89.PreQuotient // x ≠ S89.aNeg})

end S89
end PiBase.Spaces
