module

public import Mathlib.Topology.Basic
public import Mathlib.Topology.Order
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S44

/- Space 44: Nested interval topology.
See https://topology.pi-base.org/spaces/S000044.
Carrier `X = (0, 1) ⊆ ℝ`; the topology is generated by `∅`, `X`, and the nested
sequence of intervals `(0, (n+1)/(n+2))` for `n : ℕ`, i.e. `(0, 1/2), (0, 2/3),
(0, 3/4), …`. -/

/-- Nested interval topology (pi-Base S44), on the interval `(0, 1) ⊆ ℝ`. -/
def S44 : Type := ↥(Set.Ioo (0 : ℝ) 1)

/-- The generating subbasis: the whole space together with the nested intervals
`(0, (n+1)/(n+2))` for `n : ℕ`. -/
instance : TopologicalSpace S44 :=
  TopologicalSpace.generateFrom
    ({(Set.univ : Set S44)} ∪
      {s : Set S44 | ∃ n : ℕ, s = {x : S44 | (x.val : ℝ) < (n + 1) / (n + 2)}})

end S44
end PiBase.Spaces
