module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S60

/- Space 60: Pointed rational extension of ℝ.
See https://topology.pi-base.org/spaces/S000060.
The carrier is ℝ; the topology is generated by the sets {x} ∪ (ℚ ∩ U),
for U Euclidean-open in ℝ and x ∈ U. -/

/-- Pointed rational extension of ℝ (pi-Base S60). -/
def S60 : Type := ℝ

instance : TopologicalSpace S60 :=
  TopologicalSpace.generateFrom
    {s : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ ∃ x ∈ U, s = {x} ∪ (Set.range ((↑) : ℚ → ℝ) ∩ U)}

end S60
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S60 as a bundled `Space` (carrier + topology). -/
noncomputable def S60 : Space := ⟨PiBase.Spaces.S60.S60, inferInstance⟩

end PiBase.Formal
