module

public import Mathlib.Topology.Order
public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S135

/- Space 135: Radial interval topology on ℝ².
See https://topology.pi-base.org/spaces/S000135.
Generated by (1) open intervals disjoint from the origin on lines through the
origin, and (2) sets `⋃ θ ∈ [0, π), I_θ` where each `I_θ` is an open interval
about the origin on the line at angle `θ`. -/

/-- The line through the origin at angle `θ`, parametrized by signed radius `r`. -/
def S135.radialLine (θ : ℝ) : Set (ℝ × ℝ) :=
  (fun r : ℝ => (r * Real.cos θ, r * Real.sin θ)) '' Set.univ

/-- Subbasis piece 1: open intervals on a line through the origin, disjoint from
the origin itself. -/
def S135.subbasisLineIntervals : Set (Set (ℝ × ℝ)) :=
  {S | ∃ θ a b : ℝ, (b ≤ 0 ∨ 0 ≤ a) ∧
    S = (fun r : ℝ => (r * Real.cos θ, r * Real.sin θ)) '' Set.Ioo a b}

/-- Subbasis piece 2: for every choice of an open interval `(a θ, b θ)` about the
origin on each line at angle `θ ∈ [0, π)`, the union of these intervals over all
such `θ`. -/
def S135.subbasisStarUnions : Set (Set (ℝ × ℝ)) :=
  {S | ∃ a b : ℝ → ℝ, (∀ θ, a θ < 0 ∧ 0 < b θ) ∧
    S = ⋃ θ ∈ Set.Ico 0 Real.pi,
      (fun r : ℝ => (r * Real.cos θ, r * Real.sin θ)) '' Set.Ioo (a θ) (b θ)}

/-- Radial interval topology on ℝ² (pi-Base S135). -/
def S135 : Type := ℝ × ℝ

instance : TopologicalSpace S135 :=
  TopologicalSpace.generateFrom
    (S135.subbasisLineIntervals ∪ S135.subbasisStarUnions)

end S135
end PiBase.Spaces
