module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S83

/- Space 83: Line with two origins.
See https://topology.pi-base.org/spaces/S000083.
Carrier `X = ℝ ⊕ Unit`: the ordinary real line (via `Sum.inl`), whose origin `Sum.inl 0`
plays the role of the first origin `0₁`, together with one extra point `Sum.inr ()`
playing the role of the second origin `0₂`. Opens are generated by: for every Euclidean
open `U : Set ℝ`, the punctured-open image `Sum.inl '' (U \ {0})` (giving every point
`x ≠ 0` its ordinary Euclidean neighborhoods, none of which meet either origin), together
with, for every open neighborhood `U` of `0` in ℝ, the two doubled-origin basic
neighborhoods `Sum.inl '' (U \ {0}) ∪ {Sum.inl 0}` (a basic neighborhood of `0₁`) and
`Sum.inl '' (U \ {0}) ∪ {Sum.inr ()}` (a basic neighborhood of `0₂`). -/

/-- Line with two origins (pi-Base S83): the real line `ℝ`, together with one extra
point `Sum.inr ()` doubling the origin `Sum.inl 0`. -/
def S83 : Type := ℝ ⊕ Unit

/-- The generating sets for the topology on `S83`: punctured Euclidean opens (basic
neighborhoods of any point `x ≠ 0`), and, for each Euclidean open neighborhood of `0`,
the corresponding basic neighborhood of each of the two origins. -/
def S83Generators : Set (Set S83) :=
  (Set.range fun U : { U : Set ℝ // IsOpen U } => Sum.inl '' ((U : Set ℝ) \ {0})) ∪
  (Set.range fun U : { U : Set ℝ // IsOpen U ∧ (0 : ℝ) ∈ U } =>
    Sum.inl '' ((U : Set ℝ) \ {0}) ∪ {Sum.inl (0 : ℝ)}) ∪
  (Set.range fun U : { U : Set ℝ // IsOpen U ∧ (0 : ℝ) ∈ U } =>
    Sum.inl '' ((U : Set ℝ) \ {0}) ∪ {Sum.inr ()})

instance S83_top : TopologicalSpace S83 := TopologicalSpace.generateFrom S83Generators

end S83
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S83 as a bundled `Space` (carrier + topology). -/
noncomputable def S83 : Space := ⟨PiBase.Spaces.S83.S83, PiBase.Spaces.S83.S83_top⟩

end PiBase.Formal
