module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S213

/- Space 213: Pseudocircle.
See https://topology.pi-base.org/spaces/S000213.
The carrier is X = {0, 1, 2, 3} (as `Fin 4`), the complete bipartite poset K_{2,2}
with bottom elements 0, 2 and top elements 1, 3 (so 0 < 1, 0 < 3, 2 < 1, 2 < 3).
The topology is generated by the upper sets of this poset:
∅, {1}, {3}, {1,3}, {0,1,3}, {2,1,3}, X. -/

/-- Pseudocircle (pi-Base S213). -/
def S213 : Type := Fin 4

instance : TopologicalSpace S213 :=
  TopologicalSpace.generateFrom
    ({ (∅ : Set (Fin 4)), {1}, {3}, {1, 3}, {0, 1, 3}, {2, 1, 3}, Set.univ } : Set (Set (Fin 4)))

end S213
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S213 as a bundled `Space` (carrier + topology). -/
noncomputable def S213 : Space := ⟨PiBase.Spaces.S213.S213, inferInstance⟩

end PiBase.Formal
