module

public import Mathlib.Topology.Order.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S97

/- Space 97: One-point compactification of the sequential fan $S_\omega$.
See https://topology.pi-base.org/spaces/S000097.
Carrier `ω² ∪ {x, y}`: the grid `ℕ × ℕ` (via `Sum.inl`), together with two extra points
`x` (`Sum.inr false`) and `y` (`Sum.inr true`). Opens are generated by: the singletons of
`ω²` (its points are isolated), together with, for each `f : ℕ → ℕ`, the set
`{x} ∪ {⟨i,j⟩ : i ≥ f j}` (a neighborhood basis at `x`: all but finitely-many points of
each row `j`), together with, for each `n : ℕ`, the set `{y} ∪ {⟨i,j⟩ : j ≥ n}` (a
neighborhood basis at `y`: all but finitely-many rows). -/

/-- One-point compactification of the sequential fan $S_\omega$ (pi-Base S97):
the grid `ℕ × ℕ`, together with two extra points `x` and `y`. -/
def S97 : Type := (ℕ × ℕ) ⊕ Bool

/-- The generating sets for the topology on `S97`: the isolated points of `ω²`, the
neighborhood-basis sets `{x} ∪ {⟨i,j⟩ : i ≥ f j}` at `x` for each `f : ℕ → ℕ` (row `j`
cofinite in `i`), and the neighborhood-basis sets `{y} ∪ {⟨i,j⟩ : j ≥ n}` at `y` for each
`n : ℕ` (cofinitely-many rows). -/
def S97Generators : Set (Set S97) :=
  (Set.range fun p : ℕ × ℕ => ({Sum.inl p} : Set S97)) ∪
  (Set.range fun f : ℕ → ℕ =>
    (Sum.inl '' {p : ℕ × ℕ | p.1 ≥ f p.2}) ∪ {Sum.inr false}) ∪
  (Set.range fun n : ℕ =>
    (Sum.inl '' {p : ℕ × ℕ | p.2 ≥ n}) ∪ {Sum.inr true})

instance S97_top : TopologicalSpace S97 := TopologicalSpace.generateFrom S97Generators

end S97
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S97 as a bundled `Space` (carrier + topology). -/
noncomputable def S97 : Space := ⟨PiBase.Spaces.S97.S97, PiBase.Spaces.S97.S97_top⟩

end PiBase.Formal
