module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S58

/- Space 58: Indiscrete rational extension of ℝ.
See https://topology.pi-base.org/spaces/S000058.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
the sets `ℚ ∩ U` for `U` Euclidean open — finer than the Euclidean topology (S25). -/

/-- Indiscrete rational extension of ℝ (pi-Base S58). -/
def S58 : Type := ℝ

instance S58_top : TopologicalSpace S58 :=
  TopologicalSpace.generateFrom
    ({ U : Set ℝ | IsOpen U } ∪ { s : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ s = Set.range ((↑) : ℚ → ℝ) ∩ U })

end S58
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S58 as a bundled `Space` (carrier + topology). -/
noncomputable def S58 : Space := ⟨PiBase.Spaces.S58.S58, PiBase.Spaces.S58.S58_top⟩

end PiBase.Formal
