module

public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S58

/- Space 58: Indiscrete rational extension of ℝ.
See https://topology.pi-base.org/spaces/S000058.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
the sets `ℚ ∩ U` for `U` Euclidean open — finer than the Euclidean topology (S25). -/

/-- Indiscrete rational extension of ℝ (pi-Base S58). -/
def S58 : Type := ℝ

instance : TopologicalSpace S58 :=
  TopologicalSpace.generateFrom
    ({ U : Set ℝ | IsOpen U } ∪ { s : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ s = Set.range ((↑) : ℚ → ℝ) ∩ U })

end S58
end PiBase.Spaces
