module

public import Mathlib.Topology.Order
public import Mathlib.Data.Set.Countable
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S22

/- Space 22: Fortissimo space on ℝ.
See https://topology.pi-base.org/spaces/S000022.
Carrier ℝ with a distinguished point `0`: every point other than `0` is isolated,
and the neighborhoods of `0` are exactly the cocountable sets containing it — i.e. the
topology is generated by the singletons `{x}`, `x ≠ 0`, together with the cocountable
sets containing `0`. -/

/-- The Fortissimo space on ℝ (pi-Base S22): ℝ, distinguished point `0`. -/
def S22 : Type := ℝ

/-- The topology generated by the singletons of points other than `0` (making them
isolated) together with the cocountable sets containing `0` (making these exactly the
neighborhoods of `0`). -/
instance : TopologicalSpace S22 :=
  TopologicalSpace.generateFrom
    ({s : Set ℝ | ∃ x : ℝ, x ≠ 0 ∧ s = {x}} ∪
      {s : Set ℝ | (0:ℝ) ∈ s ∧ sᶜ.Countable})

end S22
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S22 as a bundled `Space` (carrier + topology). -/
noncomputable def S22 : Space := ⟨PiBase.Spaces.S22.S22, inferInstance⟩

end PiBase.Formal
