module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S19

/- Space 19: Compact Complement Topology for the Euclidean Real Numbers.
See https://topology.pi-base.org/spaces/S000019.
The topology on ℝ generated by declaring `U` open iff `ℝ \ U` is Euclidean-compact
(together with `∅`); this is coarser than the Euclidean topology (S25). -/

/-- Compact Complement Topology for the Euclidean Real Numbers (pi-Base S19). -/
def S19 : Type := ℝ

instance : TopologicalSpace S19 :=
  TopologicalSpace.generateFrom
    {U : Set ℝ | IsCompact (Set.univ \ U) ∨ U = ∅}

end S19
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S19 as a bundled `Space` (carrier + topology). -/
noncomputable def S19 : Space := ⟨PiBase.Spaces.S19.S19, inferInstance⟩

end PiBase.Formal
