module

public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Topology.Constructions.SumProd

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S70

/- Space 70: Half-disc topology.
See https://topology.pi-base.org/spaces/S000070.
Carrier `X = H ∪ L ⊆ ℝ²`, the closed upper half plane, where `H = {(x,y) : y > 0}` is the
open upper half plane and `L = {(x,y) : y = 0}` is the x-axis. The topology is generated by
the neighborhood bases: points of `H` get their usual Euclidean neighborhoods, while a point
`x ∈ L` gets neighborhoods of the form `{x} ∪ (H ∩ U)` for `U` a Euclidean-open set of `ℝ²`
containing `x`. -/

/-- The half-disc topology carrier (pi-Base S70): the closed upper half plane
`X = {(x,y) ∈ ℝ² : y ≥ 0}`. -/
def S70 : Type := {p : ℝ × ℝ // 0 ≤ p.2}

/-- The generating subbasis for the half-disc topology: Euclidean-open subsets of the open
upper half plane `H` (giving points of `H` their usual Euclidean neighborhoods), together with,
for each boundary point `x ∈ L` and each Euclidean-open `U ∋ x`, the half-disc neighborhood
`{x} ∪ (H ∩ U)`. -/
def S70.subbasis : Set (Set S70) :=
  {s | ∃ U : Set (ℝ × ℝ), IsOpen U ∧ s = {p : S70 | p.1 ∈ U ∧ 0 < p.1.2}} ∪
  {s | ∃ (x : S70) (U : Set (ℝ × ℝ)), IsOpen U ∧ x.1 ∈ U ∧ x.1.2 = 0 ∧
    s = insert x {p : S70 | p.1 ∈ U ∧ 0 < p.1.2}}

instance S70_top : TopologicalSpace S70 := TopologicalSpace.generateFrom S70.subbasis

end S70
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S70 as a bundled `Space` (carrier + topology). -/
noncomputable def S70 : Space := ⟨PiBase.Spaces.S70.S70, PiBase.Spaces.S70.S70_top⟩

end PiBase.Formal
