module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic
public import Mathlib.Data.Set.Finite.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S137

/- Space 137: Michael's subspace of Bing's Example G.
See https://topology.pi-base.org/spaces/S000137.
Let `X = 2^(2^ℝ)` (pi-Base S000136), i.e. functions `Set ℝ → Bool`; for `r : ℝ`,
`xr r` sends `S : Set ℝ` to `true` iff `r ∈ S`, and `M = range xr`. `X`'s topology
is generated by the usual product-topology subbasic opens together with the
singletons `{x}` for `x ∉ M` — points of `M` keep their usual product
neighborhoods and every point outside `M` is isolated. `F = {x : X | x(S) = 1
for only finitely many S ∈ 2^ℝ}` and `Y = M ∪ F` (this space) is the subspace
`Y` of `X`, which is closed in `X`. -/

/-- The carrier of Bing's Example G: `X = 2^(2^ℝ)`, i.e. functions `Set ℝ → Bool`. -/
def BingG : Type := Set ℝ → Bool

namespace BingG

/-- The point `xr r : Set ℝ → Bool` sends `S` to `true` iff `r ∈ S`. -/
noncomputable def xr (r : ℝ) : BingG := fun S => @decide (r ∈ S) (Classical.propDecidable _)

/-- `M`, the set of "product-topology" points `{xr r : r ∈ ℝ}` inside `X`. -/
noncomputable def M : Set BingG := Set.range xr

/-- `F = {x ∈ X : x(S) = 1 for only finitely many S ∈ 2^ℝ}`. -/
def F : Set BingG := {x : BingG | {S : Set ℝ | x S = true}.Finite}

end BingG

/-- The topology on `X`: generated by the subbasic opens of the product topology on
`Set ℝ → Bool` (discrete `Bool` factors), together with singletons of every point
outside `M` — so points of `M` retain their usual product neighborhoods and every point
of `X \ M` is isolated. -/
instance : TopologicalSpace BingG :=
  TopologicalSpace.generateFrom
    ({s : Set BingG | IsOpen[Pi.topologicalSpace] s} ∪ {s : Set BingG | ∃ x ∉ BingG.M, s = {x}})

/-- Michael's subspace of Bing's Example G (pi-Base S137): `Y = M ∪ F ⊆ X`,
with the subspace topology. This `Y` is closed in `X`. -/
def S137 : Type := ↥(BingG.M ∪ BingG.F)

instance S137_top : TopologicalSpace S137 := inferInstanceAs (TopologicalSpace ↥(BingG.M ∪ BingG.F))

end S137
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S137 as a bundled `Space` (carrier + topology). -/
noncomputable def S137 : Space := ⟨PiBase.Spaces.S137.S137, PiBase.Spaces.S137.S137_top⟩

end PiBase.Formal
