module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S51

/- Space 51: Khalimsky line.
See https://topology.pi-base.org/spaces/S000051.
On `X = ℤ`, the topology is generated by the basis
`{2i-1, 2i, 2i+1}` (for `i : ℤ`) together with the singletons `{2i+1}` (for `i : ℤ`). -/

/-- Khalimsky line (pi-Base S51). -/
def S51 : Type := ℤ

instance : TopologicalSpace S51 :=
  TopologicalSpace.generateFrom
    ({s : Set S51 | ∃ i : ℤ, s = {2 * i - 1, 2 * i, 2 * i + 1}} ∪
      {s : Set S51 | ∃ i : ℤ, s = {2 * i + 1}})

end S51
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S51 as a bundled `Space` (carrier + topology). -/
noncomputable def S51 : Space := ⟨PiBase.Spaces.S51.S51, inferInstance⟩

end PiBase.Formal
