module

public import Mathlib.Topology.Order
public import Mathlib.Data.PNat.Basic
public import Mathlib.Data.Int.GCD

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S52

/- Space 52: Relatively prime integer topology (Golomb space).
See https://topology.pi-base.org/spaces/S000052.
Carrier `X = ℤ⁺` (positive integers). For coprime `a, b : ℤ⁺`, let
`U_a(b) = {x ∈ X : a ∣ (x - b)}` (the residue class of `b` mod `a`, intersected with `X`,
matching pi-Base's `{b+na ∈ X : n ∈ ℤ}`). The topology is generated by the basis
`{U_a(b) : a, b ∈ X, gcd(a,b) = 1}`. -/

/-- Relatively prime integer topology / Golomb space (pi-Base S52): the positive integers. -/
def S52 : Type := ℕ+

/-- The basic sets `U_a(b) = {x ∈ ℤ⁺ : a ∣ (x - b)}` for coprime `a, b : ℤ⁺`, forming the
basis that generates the relatively prime integer topology. -/
def S52Generators : Set (Set S52) :=
  Set.range fun p : {p : ℕ+ × ℕ+ // Nat.gcd p.1 p.2 = 1} =>
    {x : S52 | (p.1.1 : ℤ) ∣ ((show ℕ+ from x : ℕ) : ℤ) - (p.1.2 : ℤ)}

instance S52_top : TopologicalSpace S52 := TopologicalSpace.generateFrom S52Generators

end S52
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S52 as a bundled `Space` (carrier + topology). -/
noncomputable def S52 : Space := ⟨PiBase.Spaces.S52.S52, PiBase.Spaces.S52.S52_top⟩

end PiBase.Formal
