module

public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S6

/- Space 6: Deleted integer topology on ℝ ∖ ℤ.
See https://topology.pi-base.org/spaces/S000006.
Carrier `X = ℝ ∖ ℤ`; the topology is generated by the basis
`{(n, n+1) ∣ n ∈ ℤ}` (the open unit intervals between consecutive integers). -/

/-- Deleted integer topology on `ℝ ∖ ℤ` (pi-Base S6): the carrier is the reals
with the integers removed. -/
def S6 : Type := {x : ℝ // ∀ n : ℤ, x ≠ n}

/-- The generating basis: the open intervals `(n, n+1)` between consecutive
integers, restricted to the carrier `ℝ ∖ ℤ`. -/
instance : TopologicalSpace S6 :=
  TopologicalSpace.generateFrom
    {s : Set S6 | ∃ n : ℤ, s = {x : S6 | (n : ℝ) < x.1 ∧ x.1 < n + 1}}

end S6
end PiBase.Spaces
