module

public import Mathlib.Topology.Constructions.SumProd
public import Mathlib.Topology.Order
public import Mathlib.Order.Interval.Set.Defs
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S76

/- Space 76: Sorgenfrey plane.
See https://topology.pi-base.org/spaces/S000076.
The square of the Sorgenfrey line (S43): `ℝ × ℝ`, each factor carrying the topology
generated by the basis of right half-open intervals `[a, b)`. -/

/-- The Sorgenfrey plane (pi-Base S76): the square of the Sorgenfrey line `ℝ × ℝ`. -/
def S76 : Type := ℝ × ℝ

instance S76_top : TopologicalSpace S76 :=
  @instTopologicalSpaceProd ℝ ℝ
    (TopologicalSpace.generateFrom {U : Set ℝ | ∃ a b : ℝ, U = Set.Ico a b})
    (TopologicalSpace.generateFrom {U : Set ℝ | ∃ a b : ℝ, U = Set.Ico a b})

end S76
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S76 as a bundled `Space` (carrier + topology). -/
noncomputable def S76 : Space := ⟨PiBase.Spaces.S76.S76, PiBase.Spaces.S76.S76_top⟩

end PiBase.Formal
