module

public import Mathlib.Topology.Compactification.StoneCech

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S108

/- Space 108: Stone-Čech compactification βω of the integers.
See https://topology.pi-base.org/spaces/S000108.
The carrier is the set of ultrafilters on ω = ℕ; the topology is generated by the sets
`{F : Ultrafilter ℕ | U ∈ F}` for `U ⊆ ℕ`. -/

/-- Stone-Čech compactification βω of the integers (pi-Base S108),
realized as the space of ultrafilters on `ℕ`. -/
def S108 : Type := Ultrafilter ℕ

instance : TopologicalSpace S108 :=
  TopologicalSpace.generateFrom (ultrafilterBasis ℕ)

end S108
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S108 as a bundled `Space` (carrier + topology). -/
noncomputable def S108 : Space := ⟨PiBase.Spaces.S108.S108, inferInstance⟩

end PiBase.Formal
