module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S59

/- Space 59: Indiscrete irrational extension of ℝ.
See https://topology.pi-base.org/spaces/S000059.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
the sets `D ∩ U` for `D` the irrationals and `U` Euclidean open. -/

/-- Indiscrete irrational extension of ℝ (pi-Base S59). -/
def S59 : Type := ℝ

instance : TopologicalSpace S59 :=
  TopologicalSpace.generateFrom
    ({U : Set ℝ | IsOpen U} ∪ {V : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ V = {x | Irrational x} ∩ U})

end S59
end PiBase.Spaces
