module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S59

/- Space 59: Indiscrete irrational extension of ℝ.
See https://topology.pi-base.org/spaces/S000059.
The carrier is ℝ; the topology is generated by the Euclidean open sets together with
the sets `D ∩ U` for `D` the irrationals and `U` Euclidean open. -/

/-- Indiscrete irrational extension of ℝ (pi-Base S59). -/
def S59 : Type := ℝ

instance S59_top : TopologicalSpace S59 :=
  TopologicalSpace.generateFrom
    ({U : Set ℝ | IsOpen U} ∪ {V : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ V = {x | Irrational x} ∩ U})

end S59
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S59 as a bundled `Space` (carrier + topology). -/
noncomputable def S59 : Space := ⟨PiBase.Spaces.S59.S59, PiBase.Spaces.S59.S59_top⟩

end PiBase.Formal
