module

public import Mathlib.SetTheory.Ordinal.Topology
public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.SetTheory.Cardinal.Cofinality
public import Mathlib.Topology.Constructions

@[expose] public section

open Topology Cardinal Ordinal

namespace PiBase.Spaces
namespace S138

/- Space 138: Rudin's Dowker space.
See https://topology.pi-base.org/spaces/S000138.
The subset of the box product `∏_{n<ω} (ω_{n+1}+1)` consisting of all `f` such that,
for some `i < ω`, `ω < cf(f(n)) < ω_i` for every `n`. -/

/-- The `n`-th factor `ω_{n+1} + 1`, realized as the ordinals `≤ ω_{n+1}`. -/
def S138.Factor (n : ℕ) : Type 1 := {o : Ordinal.{0} // o ≤ ω_ (n + 1 : ℕ)}

instance (n : ℕ) : TopologicalSpace (S138.Factor n) := instTopologicalSpaceSubtype

/-- The ambient box product `∏_{n<ω} (ω_{n+1}+1)`. -/
def S138.Ambient : Type 1 := ∀ n : ℕ, S138.Factor n

/-- The box topology on the ambient product: generated by all "boxes"
`∏_n U n` where every `U n` is open. -/
instance : TopologicalSpace S138.Ambient :=
  TopologicalSpace.generateFrom
    {s | ∃ U : ∀ n : ℕ, Set (S138.Factor n), (∀ n, IsOpen (U n)) ∧ s = Set.pi Set.univ U}

/-- Rudin's Dowker space (pi-Base S138): the subset of the box product
`∏_{n<ω} (ω_{n+1}+1)` of all `f` such that, for some `i < ω`,
`ω < cf(f(n)) < ω_i` for every `n`. -/
def S138 : Type 1 :=
  {f : S138.Ambient // ∃ i : ℕ, ∀ n : ℕ, ℵ₀ < Ordinal.cof (f n).1 ∧ Ordinal.cof (f n).1 < ℵ_ (i : Ordinal)}

instance : TopologicalSpace S138 := instTopologicalSpaceSubtype

end S138
end PiBase.Spaces
