module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S65

/- Space 65: Telophase topology.
See https://topology.pi-base.org/spaces/S000065.
Carrier `X = [0,1] ∪ {1*}`: the ordinary closed unit interval (via `Sum.inl`), together
with one extra right endpoint `1* = Sum.inr ()`. Opens are generated by: the usual
order-open rays `Set.Iio x` and `Set.Ioi x` on `[0,1]`, giving every point of `[0,1]`
(including `1` itself) its ordinary subspace neighborhoods, together with, for each
`a < 1`, the set `(a,1) ∪ {1*}` (a local basis at the doubled point `1*`). -/

/-- Telophase topology (pi-Base S65): the closed unit interval `[0,1]`, together with
one extra right endpoint `1* = Sum.inr ()`. -/
def S65 : Type := ↥(Set.Icc (0 : ℝ) 1) ⊕ Unit

/-- The generating sets for the topology on `S65`: order-open rays among the points of
`[0,1]`, and the doubled-point neighborhood-basis sets `(a,1) ∪ {1*}` for `a < 1`. -/
def S65Generators : Set (Set S65) :=
  (Set.range fun x : ↥(Set.Icc (0 : ℝ) 1) => Sum.inl '' Set.Iio x) ∪
  (Set.range fun x : ↥(Set.Icc (0 : ℝ) 1) => Sum.inl '' Set.Ioi x) ∪
  (Set.range fun a : ↥(Set.Icc (0 : ℝ) 1) =>
    (Sum.inl '' {x : ↥(Set.Icc (0 : ℝ) 1) | (a : ℝ) < x ∧ (x : ℝ) < 1}) ∪ {Sum.inr ()})

instance S65_top : TopologicalSpace S65 := TopologicalSpace.generateFrom S65Generators

end S65
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S65 as a bundled `Space` (carrier + topology). -/
noncomputable def S65 : Space := ⟨PiBase.Spaces.S65.S65, PiBase.Spaces.S65.S65_top⟩

end PiBase.Formal
