module

public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S61

/- Space 61: Pointed irrational extension of ℝ.
See https://topology.pi-base.org/spaces/S000061.
ℝ with the topology generated by the sets `{x} ∪ (D ∩ U)`, where `D` is the set of
irrational numbers, `U ⊆ ℝ` is Euclidean-open, and `x ∈ U`. -/

/-- Pointed irrational extension of ℝ (pi-Base S61). -/
def S61 : Type := ℝ

instance : TopologicalSpace S61 :=
  TopologicalSpace.generateFrom
    {s : Set ℝ | ∃ U : Set ℝ, IsOpen U ∧ ∃ x ∈ U, s = {x} ∪ ({y : ℝ | Irrational y} ∩ U)}

end S61
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S61 as a bundled `Space` (carrier + topology). -/
noncomputable def S61 : Space := ⟨PiBase.Spaces.S61.S61, inferInstance⟩

end PiBase.Formal
