module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Compactification.OnePoint.Basic
public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal OnePoint

namespace PiBase.Spaces
namespace S87

/- Space 87: Deleted Dieudonné plank.
See https://topology.pi-base.org/spaces/S000087.
The subspace `X = (Y × Z) \ {(ω₁, ω)}` of the Dieudonné plank `Y × Z`, where
`Y = [0, ω₁]` carries the topology with points of `[0, ω₁)` isolated and
neighborhoods of `ω₁` cocountable, and `Z = [0, ω]` carries the topology with
points of `[0, ω)` isolated and neighborhoods of `ω` cofinite (realized as
`OnePoint ℕ`, matching pi-Base S20). Note this is *not* the order topology
on `Y` (that would give the Tychonoff plank, S78) — the neighborhoods of
`ω₁` here are cocountable, a strictly finer requirement. -/

/-- The factor `[0, ω₁]` of the Dieudonné plank: ordinals at most the least
uncountable ordinal `ω₁`. -/
def S87.Y : Type 1 := {o : Ordinal.{0} // o ≤ ω₁}

/-- The distinguished top point `ω₁` of `S87.Y`. -/
noncomputable def S87.Y.top : S87.Y := ⟨ω₁, le_refl ω₁⟩

/-- Topology on `S87.Y`: generated by singletons of points below `ω₁`
(making them isolated) together with the cocountable sets containing `ω₁`
(making those exactly the neighborhoods of `ω₁`). -/
noncomputable instance : TopologicalSpace S87.Y :=
  TopologicalSpace.generateFrom
    ({s : Set S87.Y | ∃ y : S87.Y, y ≠ S87.Y.top ∧ s = {y}} ∪
      {s : Set S87.Y | S87.Y.top ∈ s ∧ sᶜ.Countable})

/-- The factor `[0, ω]` of the Dieudonné plank: the ordinal space `ω+1`,
realized as the one-point compactification of the discrete space `ℕ`
(pi-Base S20). -/
def S87.Z : Type := OnePoint ℕ

instance : TopologicalSpace S87.Z := inferInstanceAs (TopologicalSpace (OnePoint ℕ))

/-- The corner point `(ω₁, ω)` of the Dieudonné plank `S87.Y × S87.Z` that
gets deleted. -/
noncomputable def S87.corner : S87.Y × S87.Z := (S87.Y.top, (∞ : OnePoint ℕ))

/-- Deleted Dieudonné plank (pi-Base S87): the Dieudonné plank
`S87.Y × S87.Z` with its corner point `(ω₁, ω)` removed, as a subtype with
the subspace topology. -/
def S87 : Type 1 := {p : S87.Y × S87.Z // p ≠ S87.corner}

noncomputable instance : TopologicalSpace S87 :=
  inferInstanceAs (TopologicalSpace {p : S87.Y × S87.Z // p ≠ S87.corner})

end S87
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S87 as a bundled `Space` (carrier + topology). -/
noncomputable def S87 : Space := ⟨PiBase.Spaces.S87.S87, inferInstance⟩

end PiBase.Formal
