module

public import Mathlib.Order.PiLex
public import Mathlib.Topology.Order.Basic
public import Mathlib.Topology.Instances.Real.Lemmas

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S212

/- Space 212: Lexicographically ordered Hilbert cube [0,1]^ω.
See https://topology.pi-base.org/spaces/S000212.
The carrier is X = [0,1]^ω = (ℕ → [0,1]), ordered lexicographically (comparing coordinates
in increasing index order, the first difference decides), and topologized with the
corresponding order topology (generated by the open rays of the lexicographic order). -/

/-- The Hilbert cube `[0,1]^ω` as a set of functions `ℕ → ℝ`, lexicographically ordered
(pi-Base S212). -/
def S212 : Type := Lex (ℕ → Set.Icc (0 : ℝ) 1)

noncomputable instance : LinearOrder S212 :=
  inferInstanceAs (LinearOrder (Lex (ℕ → Set.Icc (0 : ℝ) 1)))

noncomputable instance : TopologicalSpace S212 := Preorder.topology S212

end S212
end PiBase.Spaces
