module

public import Mathlib.Order.PiLex
public import Mathlib.Topology.Order.Basic
public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S212

/- Space 212: Lexicographically ordered Hilbert cube [0,1]^ω.
See https://topology.pi-base.org/spaces/S000212.
The carrier is X = [0,1]^ω = (ℕ → [0,1]), ordered lexicographically (comparing coordinates
in increasing index order, the first difference decides), and topologized with the
corresponding order topology (generated by the open rays of the lexicographic order). -/

/-- The Hilbert cube `[0,1]^ω` as a set of functions `ℕ → ℝ`, lexicographically ordered
(pi-Base S212). -/
def S212 : Type := Lex (ℕ → Set.Icc (0 : ℝ) 1)

noncomputable instance : LinearOrder S212 :=
  inferInstanceAs (LinearOrder (Lex (ℕ → Set.Icc (0 : ℝ) 1)))

noncomputable instance S212_top : TopologicalSpace S212 := Preorder.topology S212

end S212
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S212 as a bundled `Space` (carrier + topology). -/
noncomputable def S212 : Space := ⟨PiBase.Spaces.S212.S212, PiBase.Spaces.S212.S212_top⟩

end PiBase.Formal
