module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology Ordinal

namespace PiBase.Spaces
namespace S217

/- Space 217: Left ray topology on ω₁.
See https://topology.pi-base.org/spaces/S000217.
The set of ordinals below the least uncountable ordinal ω₁ (as in S35), topologized
by the basis of left rays [0,α] = {x | x ≤ α}; equivalently, the open sets are the
downward-closed subsets of ω₁ (the Alexandrov topology for the reverse order). -/

/-- The ordinals below the least uncountable ordinal ω₁ (as in pi-Base S35), the
underlying carrier of the left ray topology here. -/
def S217 : Type 1 := {o : Ordinal.{0} // o < ω₁}

noncomputable instance : LinearOrder S217 :=
  inferInstanceAs (LinearOrder {o : Ordinal.{0} // o < ω₁})

/-- Left ray topology on ω₁ (pi-Base S217): generated by the basis of left rays
`[0,α] = Set.Iic α` for `α ∈ ω₁`. The resulting open sets are exactly the
downward-closed subsets of ω₁. -/
noncomputable instance S217_top : TopologicalSpace S217 :=
  TopologicalSpace.generateFrom {s : Set S217 | ∃ a : S217, s = Set.Iic a}

end S217
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S217 as a bundled `Space` (carrier + topology). -/
noncomputable def S217 : Space := ⟨PiBase.Spaces.S217.S217, PiBase.Spaces.S217.S217_top⟩

end PiBase.Formal
