module

public import Mathlib.Topology.Instances.Real.Lemmas

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S159

/- Space 159: Right "open-ray" topology on [0,1].
See https://topology.pi-base.org/spaces/S000159.
Carrier [0,1] ⊆ ℝ; topology generated by the rays {x | a < x} for a : ℝ, restricted
to the carrier, which realizes exactly X and (a,1] as the open sets. -/

/-- Right "open-ray" topology on `[0,1]` (pi-Base S159). -/
def S159 : Type := Set.Icc (0 : ℝ) 1

instance : TopologicalSpace S159 :=
  TopologicalSpace.generateFrom {s : Set S159 | ∃ a : ℝ, s = {x : S159 | a < x.1}}

end S159
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S159 as a bundled `Space` (carrier + topology). -/
noncomputable def S159 : Space := ⟨PiBase.Spaces.S159.S159, inferInstance⟩

end PiBase.Formal
