module

public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S204

/- Space 204: Three-point set with the basis $\{\{0,1\},X\}$.
See https://topology.pi-base.org/spaces/S000204.
X = {0, 1, 2} with open sets generated by the subbasis {{0, 1}} (giving exactly
the opens ∅, {0, 1}, X). -/

/-- Three-point set with the basis `{{0,1}, X}` (pi-Base S204). -/
def S204 : Type := Fin 3

instance S204_top : TopologicalSpace S204 :=
  TopologicalSpace.generateFrom {({0, 1} : Set (Fin 3))}

end S204
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S204 as a bundled `Space` (carrier + topology). -/
noncomputable def S204 : Space := ⟨PiBase.Spaces.S204.S204, PiBase.Spaces.S204.S204_top⟩

end PiBase.Formal
