module

public import Mathlib.Topology.Instances.Real.Lemmas
public import Mathlib.Data.PNat.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S206

/- Space 206: Deleted Sequence of Intervals Topology.
See https://topology.pi-base.org/spaces/S000206.
Let `A = ⋃ n, [1/(2n+1), 1/(2n)]`. The topology on `ℝ` is generated by the standard open
sets together with the single extra set `ℝ \ A`. -/

/-- The set `A = ⋃_{n=1}^∞ [1/(2n+1), 1/(2n)]` deleted to form the topology. -/
def S206.A : Set ℝ := ⋃ n : ℕ+, Set.Icc (1 / (2 * (n : ℝ) + 1)) (1 / (2 * (n : ℝ)))

/-- Deleted Sequence of Intervals Topology (pi-Base S206). -/
def S206 : Type := ℝ

instance : TopologicalSpace S206 :=
  TopologicalSpace.generateFrom
    ({s : Set ℝ | IsOpen s} ∪ {(Set.univ \ S206.A : Set ℝ)})

end S206
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S206 as a bundled `Space` (carrier + topology). -/
noncomputable def S206 : Space := ⟨PiBase.Spaces.S206.S206, inferInstance⟩

end PiBase.Formal
