module

public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Order
public import Mathlib.Data.Real.Basic

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S82

/- Space 82: Sum of continuum-many Right Ray Topology on the Reals.
See https://topology.pi-base.org/spaces/S000082.
The topological sum (disjoint union) of `ℝ`-many copies of pi-Base S42 (the right ray
topology on the reals, generated by the basis of right rays `B_y = {x : y < x}`);
the index set `ℝ` has cardinality the continuum. -/

/-- Right ray topology on the reals (pi-Base S42), used here as the summand. -/
def RightRay : Type := ℝ

instance : TopologicalSpace RightRay :=
  TopologicalSpace.generateFrom {s : Set ℝ | ∃ y : ℝ, s = Set.Ioi y}

/-- Sum of continuum-many Right Ray Topology on the Reals (pi-Base S82). -/
def S82 : Type := Σ _ : ℝ, RightRay

instance S82_top : TopologicalSpace S82 := inferInstanceAs (TopologicalSpace (Σ _ : ℝ, RightRay))

end S82
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S82 as a bundled `Space` (carrier + topology). -/
noncomputable def S82 : Space := ⟨PiBase.Spaces.S82.S82, PiBase.Spaces.S82.S82_top⟩

end PiBase.Formal
