module

public import Mathlib.Data.ENat.Basic
public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S166

/- Space 166: Left ray topology on $\omega+1$.
See https://topology.pi-base.org/spaces/S000166.
The open sets are generated by the left rays `[0, a)` for `a` in `ω+1 = ℕ∞`, i.e. the
Alexandrov topology for the reverse ordering (open sets = downward-closed subsets). -/

/-- Left ray topology on `ω+1` (pi-Base S166). Carrier is `ℕ∞ = WithTop ℕ`, the order type
`ω+1`. -/
def S166 : Type := ℕ∞

instance S166_top : TopologicalSpace S166 :=
  TopologicalSpace.generateFrom {s : Set ℕ∞ | ∃ a : ℕ∞, s = Set.Iio a}

end S166
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S166 as a bundled `Space` (carrier + topology). -/
noncomputable def S166 : Space := ⟨PiBase.Spaces.S166.S166, PiBase.Spaces.S166.S166_top⟩

end PiBase.Formal
