module

public import Mathlib.Topology.Basic
public import Mathlib.Topology.Order

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S49

/- Space 49: Divisor topology.
See https://topology.pi-base.org/spaces/S000049.
Carrier `X = {x : ℕ // x ≥ 2}`; the topology is generated by the sets
`B_n = {x ∈ X : x divides n}` for each `n ∈ X`. -/

/-- Divisor topology (pi-Base S49), on `X = {x ∈ ℕ : x ≥ 2}`. -/
def S49 : Type := {x : ℕ // x ≥ 2}

/-- The generating subbasis: for each `n : S49`, the set of divisors of `n` in `X`. -/
instance : TopologicalSpace S49 :=
  TopologicalSpace.generateFrom
    {s : Set S49 | ∃ n : S49, s = {x : S49 | x.val ∣ n.val}}

end S49
end PiBase.Spaces
