module

public import Mathlib.Topology.Constructions

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S186

/- Space 186: Converging sequence of non-Hausdorff spaces.
See https://topology.pi-base.org/spaces/S000186.
Let `Y97` be a copy of the one-point compactification of the sequential fan (pi-Base S97):
carrier `(ℕ × ℕ) ⊕ Bool` (the grid `ω²`, plus two extra points `x`, `y`), topologized by:
the singletons of `ω²` (isolated points), together with, for each `f : ℕ → ℕ`, the set
`{x} ∪ {⟨i,j⟩ : i ≥ f j}`, together with, for each `n : ℕ`, the set `{y} ∪ {⟨i,j⟩ : j ≥ n}`.
This definition is inlined (rather than imported) to keep this file self-contained against
the Mathlib cache alone.
Carrier `X = (Y97 × ω) ∪ {∞}`, realized as `Y97 × ℕ` (via `Sum.inl`) together with one extra
point `∞` (`Sum.inr ()`). Opens are generated by: every open set of `Y97 × ω` in the product
topology (so `Y97 × ω` is open with the product topology), together with, for each `n : ℕ`,
the set `(Y97 × (ω \ n)) ∪ {∞}` (a neighborhood basis at `∞`: all but finitely-many copies of
`Y97`). -/

/-- One-point compactification of the sequential fan $S_\omega$ (pi-Base S97), inlined here
as the space `Y` referenced by S186: the grid `ℕ × ℕ`, together with two extra points
`x` (`Sum.inr false`) and `y` (`Sum.inr true`). -/
def S186.Y97 : Type := (ℕ × ℕ) ⊕ Bool

/-- The generating sets for the topology on `Y97`: the isolated points of `ω²`, the
neighborhood-basis sets `{x} ∪ {⟨i,j⟩ : i ≥ f j}` at `x` for each `f : ℕ → ℕ`, and the
neighborhood-basis sets `{y} ∪ {⟨i,j⟩ : j ≥ n}` at `y` for each `n : ℕ`. -/
def S186.Y97Generators : Set (Set S186.Y97) :=
  (Set.range fun p : ℕ × ℕ => ({Sum.inl p} : Set S186.Y97)) ∪
  (Set.range fun f : ℕ → ℕ =>
    (Sum.inl '' {p : ℕ × ℕ | p.1 ≥ f p.2}) ∪ {Sum.inr false}) ∪
  (Set.range fun n : ℕ =>
    (Sum.inl '' {p : ℕ × ℕ | p.2 ≥ n}) ∪ {Sum.inr true})

instance : TopologicalSpace S186.Y97 := TopologicalSpace.generateFrom S186.Y97Generators

/-- Converging sequence of non-Hausdorff spaces (pi-Base S186):
`(Y × ω) ∪ {∞}`, where `Y` is a copy of `S97`. -/
def S186 : Type := (S186.Y97 × ℕ) ⊕ Unit

/-- The generating sets for the topology on `S186`: every open subset of the product
`Y97 × ℕ` (making `Y × ω` open with the product topology), together with, for each
`n : ℕ`, the set `(Y × (ω \ n)) ∪ {∞}` (a neighborhood basis at `∞` covering all but
finitely-many copies of `Y`). -/
def S186Generators : Set (Set S186) :=
  (Sum.inl '' ·) '' {U : Set (S186.Y97 × ℕ) | IsOpen U} ∪
  (Set.range fun n : ℕ =>
    (Sum.inl '' (Set.univ ×ˢ {m : ℕ | m ≥ n})) ∪ {Sum.inr ()})

instance S186_top : TopologicalSpace S186 := TopologicalSpace.generateFrom S186Generators

end S186
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S186 as a bundled `Space` (carrier + topology). -/
noncomputable def S186 : Space := ⟨PiBase.Spaces.S186.S186, PiBase.Spaces.S186.S186_top⟩

end PiBase.Formal
