module

public import Mathlib.Analysis.Complex.Circle

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology

namespace PiBase.Spaces
namespace S209

/- Space 209: Circle with two origins.
See https://topology.pi-base.org/spaces/S000209.
Carrier `X = Circle ⊕ Unit`: the unit circle `Circle` (via `Sum.inl`), where the fixed
basepoint `Sum.inl 1` plays the role of the first origin `0₁`, together with one extra
point `Sum.inr ()` playing the role of the second origin `0₂`. Opens are generated by:
for every open `U : Set Circle`, the punctured-open image `Sum.inl '' (U \ {1})` (giving
every point `x ≠ 1` its ordinary neighborhoods, none of which meet either origin),
together with, for every open neighborhood `U` of `1` in `Circle`, the two doubled-origin
basic neighborhoods `Sum.inl '' (U \ {1}) ∪ {Sum.inl 1}` (a basic neighborhood of `0₁`)
and `Sum.inl '' (U \ {1}) ∪ {Sum.inr ()}` (a basic neighborhood of `0₂`). -/

/-- Circle with two origins (pi-Base S209): the unit circle `Circle`, together with one
extra point `Sum.inr ()` doubling the basepoint `Sum.inl 1`. -/
def S209 : Type := Circle ⊕ Unit

/-- The generating sets for the topology on `S209`: punctured opens of `Circle` (basic
neighborhoods of any point `x ≠ 1`), and, for each open neighborhood of `1`, the
corresponding basic neighborhood of each of the two origins. -/
def S209Generators : Set (Set S209) :=
  (Set.range fun U : { U : Set Circle // IsOpen U } => Sum.inl '' ((U : Set Circle) \ {1})) ∪
  (Set.range fun U : { U : Set Circle // IsOpen U ∧ (1 : Circle) ∈ U } =>
    Sum.inl '' ((U : Set Circle) \ {1}) ∪ {Sum.inl (1 : Circle)}) ∪
  (Set.range fun U : { U : Set Circle // IsOpen U ∧ (1 : Circle) ∈ U } =>
    Sum.inl '' ((U : Set Circle) \ {1}) ∪ {Sum.inr ()})

instance : TopologicalSpace S209 := TopologicalSpace.generateFrom S209Generators

end S209
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S209 as a bundled `Space` (carrier + topology). -/
noncomputable def S209 : Space := ⟨PiBase.Spaces.S209.S209, inferInstance⟩

end PiBase.Formal
