module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Order

public import PiBaseLean.Spaces.Bundled.Defs

@[expose] public section

open Topology
open Ordinal

namespace PiBase.Spaces
namespace S221

/- Space 221: Right "open-ray" topology on ω₁.
See https://topology.pi-base.org/spaces/S000221.
Carrier X = ω₁ = [0, ω₁) with its usual order; opens are ∅, X, and the "open rays"
(α, →) for α ∈ X, i.e. the topology generated by the subbasis of all `Set.Ioi α`. -/

/-- Right "open-ray" topology on `ω₁` (pi-Base S221). -/
noncomputable def S221 : Type := (ω₁ : Ordinal.{0}).ToType

noncomputable instance : LinearOrder S221 :=
  inferInstanceAs (LinearOrder (ω₁ : Ordinal.{0}).ToType)

instance : TopologicalSpace S221 :=
  TopologicalSpace.generateFrom (Set.range (fun a : S221 => Set.Ioi a))

end S221
end PiBase.Spaces

namespace PiBase.Formal

/-- π-Base S221 as a bundled `Space` (carrier + topology). -/
noncomputable def S221 : Space := ⟨PiBase.Spaces.S221.S221, inferInstance⟩

end PiBase.Formal
