module

public import Mathlib.SetTheory.Cardinal.Aleph
public import Mathlib.Topology.Compactification.OnePoint.Basic
public import Mathlib.Data.Set.Countable

@[expose] public section

open Topology Cardinal

namespace PiBase.Spaces
namespace S191

/- Space 191: Dieudonné plank.
See https://topology.pi-base.org/spaces/S000191.
Carrier: the product `X = Y × Z` where `Y = [0, ω₁]` carries the topology making every
point below `ω₁` isolated and every neighborhood of `ω₁` cocountable (the Fortissimo
space, pi-Base S155), and `Z = [0, ω]` carries the topology making every point below `ω`
isolated and every neighborhood of `ω` cofinite (the Fort space on a countably infinite
set, pi-Base S20, realized as the one-point compactification `OnePoint ℕ`). The topology
on `X` is the product topology. -/

/-- The factor `Y = [0, ω₁]`: the canonical type of cardinality `ℵ₁`, to be topologized
as the Fortissimo space (pi-Base S155). -/
def PlankY : Type := (ℵ₁ : Cardinal).ord.ToType

noncomputable instance instOrderBotPlankY :
    OrderBot (ℵ₁ : Cardinal).ord.ToType :=
  Cardinal.toTypeOrderBot (Cardinal.aleph0_pos.trans Cardinal.aleph0_lt_aleph_one).ne'

/-- The distinguished point `ω₁ ∈ Y`: taken to be the least element of the canonical
well-ordering underlying the carrier (matching pi-Base S155). -/
noncomputable def plankOmega1 : PlankY := (⊥ : (ℵ₁ : Cardinal).ord.ToType)

/-- The topology on `Y`: generated by the singletons of points other than `ω₁` (making
them isolated) together with the cocountable sets containing `ω₁` (making these exactly
the neighborhoods of `ω₁`). -/
instance instTopologicalSpacePlankY : TopologicalSpace PlankY :=
  TopologicalSpace.generateFrom
    ({s : Set PlankY | ∃ x : PlankY, x ≠ plankOmega1 ∧ s = {x}} ∪
      {s : Set PlankY | plankOmega1 ∈ s ∧ sᶜ.Countable})

/-- The factor `Z = [0, ω]`: the one-point compactification of the discrete space `ℕ`,
i.e. the Fort space on a countably infinite set (pi-Base S20). -/
def PlankZ : Type := OnePoint ℕ

instance instTopologicalSpacePlankZ : TopologicalSpace PlankZ :=
  inferInstanceAs (TopologicalSpace (OnePoint ℕ))

/-- Dieudonné plank (pi-Base S191): the product `Y × Z`. -/
def S191 : Type := PlankY × PlankZ

instance : TopologicalSpace S191 :=
  inferInstanceAs (TopologicalSpace (PlankY × PlankZ))

end S191
end PiBase.Spaces
